/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables;


import com.inspector.ws.db.schema.Indexes;
import com.inspector.ws.db.schema.Keys;
import com.inspector.ws.db.schema.Public;
import com.inspector.ws.db.schema.tables.records.TabSolSelloLlegadaRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row20;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolSelloLlegada extends TableImpl<TabSolSelloLlegadaRecord> {

    private static final long serialVersionUID = 425052627;

    /**
     * The reference instance of <code>public.tab_sol_sello_llegada</code>
     */
    public static final TabSolSelloLlegada TAB_SOL_SELLO_LLEGADA = new TabSolSelloLlegada();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TabSolSelloLlegadaRecord> getRecordType() {
        return TabSolSelloLlegadaRecord.class;
    }

    /**
     * The column <code>public.tab_sol_sello_llegada.id_sol_sello_llegada</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, Long> ID_SOL_SELLO_LLEGADA = createField(DSL.name("id_sol_sello_llegada"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.candado_plastico</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> CANDADO_PLASTICO = createField(DSL.name("candado_plastico"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.candado_botella</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> CANDADO_BOTELLA = createField(DSL.name("candado_botella"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.sticker_llegada</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> STICKER_LLEGADA = createField(DSL.name("sticker_llegada"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.rastreo_satelital</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> RASTREO_SATELITAL = createField(DSL.name("rastreo_satelital"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.sello_cadena</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> SELLO_CADENA = createField(DSL.name("sello_cadena"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.sticker_naviera</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> STICKER_NAVIERA = createField(DSL.name("sticker_naviera"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.sello_arribo_01</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> SELLO_ARRIBO_01 = createField(DSL.name("sello_arribo_01"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.sello_llegada_2</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> SELLO_LLEGADA_2 = createField(DSL.name("sello_llegada_2"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.sticker_patio_ventolera_1</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> STICKER_PATIO_VENTOLERA_1 = createField(DSL.name("sticker_patio_ventolera_1"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.sticker_patio_ventolera_2</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> STICKER_PATIO_VENTOLERA_2 = createField(DSL.name("sticker_patio_ventolera_2"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.nro_serie</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> NRO_SERIE = createField(DSL.name("nro_serie"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.candado_exportador</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> CANDADO_EXPORTADOR = createField(DSL.name("candado_exportador"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.observacion</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> OBSERVACION = createField(DSL.name("observacion"), org.jooq.impl.SQLDataType.VARCHAR(1000).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.estado</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, String> ESTADO = createField(DSL.name("estado"), org.jooq.impl.SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.fecha_ingreso</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, LocalDateTime> FECHA_INGRESO = createField(DSL.name("fecha_ingreso"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.fecha_modifica</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, LocalDateTime> FECHA_MODIFICA = createField(DSL.name("fecha_modifica"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.usuario_ingreso</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, Integer> USUARIO_INGRESO = createField(DSL.name("usuario_ingreso"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.usuario_modifica</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, Integer> USUARIO_MODIFICA = createField(DSL.name("usuario_modifica"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_sello_llegada.id_solicitud</code>.
     */
    public final TableField<TabSolSelloLlegadaRecord, Long> ID_SOLICITUD = createField(DSL.name("id_solicitud"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.tab_sol_sello_llegada</code> table reference
     */
    public TabSolSelloLlegada() {
        this(DSL.name("tab_sol_sello_llegada"), null);
    }

    /**
     * Create an aliased <code>public.tab_sol_sello_llegada</code> table reference
     */
    public TabSolSelloLlegada(String alias) {
        this(DSL.name(alias), TAB_SOL_SELLO_LLEGADA);
    }

    /**
     * Create an aliased <code>public.tab_sol_sello_llegada</code> table reference
     */
    public TabSolSelloLlegada(Name alias) {
        this(alias, TAB_SOL_SELLO_LLEGADA);
    }

    private TabSolSelloLlegada(Name alias, Table<TabSolSelloLlegadaRecord> aliased) {
        this(alias, aliased, null);
    }

    private TabSolSelloLlegada(Name alias, Table<TabSolSelloLlegadaRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TabSolSelloLlegada(Table<O> child, ForeignKey<O, TabSolSelloLlegadaRecord> key) {
        super(child, key, TAB_SOL_SELLO_LLEGADA);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TAB_SOL_SELLO_LLEGADA_PKEY);
    }

    @Override
    public UniqueKey<TabSolSelloLlegadaRecord> getPrimaryKey() {
        return Keys.TAB_SOL_SELLO_LLEGADA_PKEY;
    }

    @Override
    public List<UniqueKey<TabSolSelloLlegadaRecord>> getKeys() {
        return Arrays.<UniqueKey<TabSolSelloLlegadaRecord>>asList(Keys.TAB_SOL_SELLO_LLEGADA_PKEY);
    }

    @Override
    public List<ForeignKey<TabSolSelloLlegadaRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TabSolSelloLlegadaRecord, ?>>asList(Keys.TAB_SOL_SELLO_LLEGADA__TAB_SOL_SELLO_LLEGADA_USUARIO_INGRESO_FKEY, Keys.TAB_SOL_SELLO_LLEGADA__TAB_SOL_SELLO_LLEGADA_USUARIO_MODIFICA_FKEY, Keys.TAB_SOL_SELLO_LLEGADA__TAB_SOL_SELLO_LLEGADA_ID_SOLICITUD_FKEY);
    }

    public TabUsuario tabSolSelloLlegada_TabSolSelloLlegadaUsuarioIngresoFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_SELLO_LLEGADA__TAB_SOL_SELLO_LLEGADA_USUARIO_INGRESO_FKEY);
    }

    public TabUsuario tabSolSelloLlegada_TabSolSelloLlegadaUsuarioModificaFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_SELLO_LLEGADA__TAB_SOL_SELLO_LLEGADA_USUARIO_MODIFICA_FKEY);
    }

    public TabSolicitud tabSolicitud() {
        return new TabSolicitud(this, Keys.TAB_SOL_SELLO_LLEGADA__TAB_SOL_SELLO_LLEGADA_ID_SOLICITUD_FKEY);
    }

    @Override
    public TabSolSelloLlegada as(String alias) {
        return new TabSolSelloLlegada(DSL.name(alias), this);
    }

    @Override
    public TabSolSelloLlegada as(Name alias) {
        return new TabSolSelloLlegada(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolSelloLlegada rename(String name) {
        return new TabSolSelloLlegada(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolSelloLlegada rename(Name name) {
        return new TabSolSelloLlegada(name, null);
    }

    // -------------------------------------------------------------------------
    // Row20 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row20<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long> fieldsRow() {
        return (Row20) super.fieldsRow();
    }
}
