/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables;


import com.inspector.ws.db.schema.Indexes;
import com.inspector.ws.db.schema.Keys;
import com.inspector.ws.db.schema.Public;
import com.inspector.ws.db.schema.tables.records.TabSolConsolidadoGanchoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolConsolidadoGancho extends TableImpl<TabSolConsolidadoGanchoRecord> {

    private static final long serialVersionUID = -49238959;

    /**
     * The reference instance of <code>public.tab_sol_consolidado_gancho</code>
     */
    public static final TabSolConsolidadoGancho TAB_SOL_CONSOLIDADO_GANCHO = new TabSolConsolidadoGancho();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TabSolConsolidadoGanchoRecord> getRecordType() {
        return TabSolConsolidadoGanchoRecord.class;
    }

    /**
     * The column <code>public.tab_sol_consolidado_gancho.id_sol_consolidado_gancho</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Long> ID_SOL_CONSOLIDADO_GANCHO = createField(DSL.name("id_sol_consolidado_gancho"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.en_funde</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, String> EN_FUNDE = createField(DSL.name("en_funde"), org.jooq.impl.SQLDataType.VARCHAR(50).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.racimo_cosechado</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> RACIMO_COSECHADO = createField(DSL.name("racimo_cosechado"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.racimo_rechazado</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> RACIMO_RECHAZADO = createField(DSL.name("racimo_rechazado"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.racimo_procesado</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> RACIMO_PROCESADO = createField(DSL.name("racimo_procesado"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.mutante</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> MUTANTE = createField(DSL.name("mutante"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.spacklin</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> SPACKLIN = createField(DSL.name("spacklin"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.punta_amarilla</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> PUNTA_AMARILLA = createField(DSL.name("punta_amarilla"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.crema</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> CREMA = createField(DSL.name("crema"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.mancha_roja</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> MANCHA_ROJA = createField(DSL.name("mancha_roja"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.alterado</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> ALTERADO = createField(DSL.name("alterado"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.pobre</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> POBRE = createField(DSL.name("pobre"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.caido</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> CAIDO = createField(DSL.name("caido"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.sobre_grado</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> SOBRE_GRADO = createField(DSL.name("sobre_grado"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.bajo_grado</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> BAJO_GRADO = createField(DSL.name("bajo_grado"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.mosaico</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> MOSAICO = createField(DSL.name("mosaico"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.rasguno_animal</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> RASGUNO_ANIMAL = createField(DSL.name("rasguno_animal"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.explosivo</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> EXPLOSIVO = createField(DSL.name("explosivo"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.herwinea</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> HERWINEA = createField(DSL.name("herwinea"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.sin_cinta</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> SIN_CINTA = createField(DSL.name("sin_cinta"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.cochinilla</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> COCHINILLA = createField(DSL.name("cochinilla"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.escama</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> ESCAMA = createField(DSL.name("escama"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.fumagina</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> FUMAGINA = createField(DSL.name("fumagina"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.pesonudo</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> PESONUDO = createField(DSL.name("pesonudo"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.observacion</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, String> OBSERVACION = createField(DSL.name("observacion"), org.jooq.impl.SQLDataType.VARCHAR(1000).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.estado</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, String> ESTADO = createField(DSL.name("estado"), org.jooq.impl.SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.fecha_ingreso</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, LocalDateTime> FECHA_INGRESO = createField(DSL.name("fecha_ingreso"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.fecha_modifica</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, LocalDateTime> FECHA_MODIFICA = createField(DSL.name("fecha_modifica"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.usuario_ingreso</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> USUARIO_INGRESO = createField(DSL.name("usuario_ingreso"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.usuario_modifica</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Integer> USUARIO_MODIFICA = createField(DSL.name("usuario_modifica"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.id_solicitud</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Long> ID_SOLICITUD = createField(DSL.name("id_solicitud"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * The column <code>public.tab_sol_consolidado_gancho.id_sol_productor</code>.
     */
    public final TableField<TabSolConsolidadoGanchoRecord, Long> ID_SOL_PRODUCTOR = createField(DSL.name("id_sol_productor"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.tab_sol_consolidado_gancho</code> table reference
     */
    public TabSolConsolidadoGancho() {
        this(DSL.name("tab_sol_consolidado_gancho"), null);
    }

    /**
     * Create an aliased <code>public.tab_sol_consolidado_gancho</code> table reference
     */
    public TabSolConsolidadoGancho(String alias) {
        this(DSL.name(alias), TAB_SOL_CONSOLIDADO_GANCHO);
    }

    /**
     * Create an aliased <code>public.tab_sol_consolidado_gancho</code> table reference
     */
    public TabSolConsolidadoGancho(Name alias) {
        this(alias, TAB_SOL_CONSOLIDADO_GANCHO);
    }

    private TabSolConsolidadoGancho(Name alias, Table<TabSolConsolidadoGanchoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TabSolConsolidadoGancho(Name alias, Table<TabSolConsolidadoGanchoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TabSolConsolidadoGancho(Table<O> child, ForeignKey<O, TabSolConsolidadoGanchoRecord> key) {
        super(child, key, TAB_SOL_CONSOLIDADO_GANCHO);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TAB_SOL_CONSOLIDADO_GANCHO_PKEY);
    }

    @Override
    public UniqueKey<TabSolConsolidadoGanchoRecord> getPrimaryKey() {
        return Keys.TAB_SOL_CONSOLIDADO_GANCHO_PKEY;
    }

    @Override
    public List<UniqueKey<TabSolConsolidadoGanchoRecord>> getKeys() {
        return Arrays.<UniqueKey<TabSolConsolidadoGanchoRecord>>asList(Keys.TAB_SOL_CONSOLIDADO_GANCHO_PKEY);
    }

    @Override
    public List<ForeignKey<TabSolConsolidadoGanchoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TabSolConsolidadoGanchoRecord, ?>>asList(Keys.TAB_SOL_CONSOLIDADO_GANCHO__TAB_SOL_CONSOLIDADO_GANCHO_USUARIO_INGRESO_FKEY, Keys.TAB_SOL_CONSOLIDADO_GANCHO__TAB_SOL_CONSOLIDADO_GANCHO_USUARIO_MODIFICA_FKEY);
    }

    public TabUsuario tabSolConsolidadoGancho_TabSolConsolidadoGanchoUsuarioIngresoFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_CONSOLIDADO_GANCHO__TAB_SOL_CONSOLIDADO_GANCHO_USUARIO_INGRESO_FKEY);
    }

    public TabUsuario tabSolConsolidadoGancho_TabSolConsolidadoGanchoUsuarioModificaFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_CONSOLIDADO_GANCHO__TAB_SOL_CONSOLIDADO_GANCHO_USUARIO_MODIFICA_FKEY);
    }

    @Override
    public TabSolConsolidadoGancho as(String alias) {
        return new TabSolConsolidadoGancho(DSL.name(alias), this);
    }

    @Override
    public TabSolConsolidadoGancho as(Name alias) {
        return new TabSolConsolidadoGancho(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolConsolidadoGancho rename(String name) {
        return new TabSolConsolidadoGancho(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolConsolidadoGancho rename(Name name) {
        return new TabSolConsolidadoGancho(name, null);
    }
}
