/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables;


import com.inspector.ws.db.schema.Indexes;
import com.inspector.ws.db.schema.Keys;
import com.inspector.ws.db.schema.Public;
import com.inspector.ws.db.schema.tables.records.TabSolCalDefectoSeleccionRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolCalDefectoSeleccion extends TableImpl<TabSolCalDefectoSeleccionRecord> {

    private static final long serialVersionUID = -54320637;

    /**
     * The reference instance of <code>public.tab_sol_cal_defecto_seleccion</code>
     */
    public static final TabSolCalDefectoSeleccion TAB_SOL_CAL_DEFECTO_SELECCION = new TabSolCalDefectoSeleccion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TabSolCalDefectoSeleccionRecord> getRecordType() {
        return TabSolCalDefectoSeleccionRecord.class;
    }

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.id_sol_cal_defecto_seleccion</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Long> ID_SOL_CAL_DEFECTO_SELECCION = createField(DSL.name("id_sol_cal_defecto_seleccion"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.peso</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Float> PESO = createField(DSL.name("peso"), org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.num_gancho_inspeccionado</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> NUM_GANCHO_INSPECCIONADO = createField(DSL.name("num_gancho_inspeccionado"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ph</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, String> PH = createField(DSL.name("ph"), org.jooq.impl.SQLDataType.VARCHAR(3).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.sr</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> SR = createField(DSL.name("sr"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.br</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> BR = createField(DSL.name("br"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ni</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> NI = createField(DSL.name("ni"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.mf</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> MF = createField(DSL.name("mf"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ct</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> CT = createField(DSL.name("ct"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.fl</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> FL = createField(DSL.name("fl"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.dp</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> DP = createField(DSL.name("dp"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ug</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> UG = createField(DSL.name("ug"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.og</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> OG = createField(DSL.name("og"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ls</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> LS = createField(DSL.name("ls"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.lg</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> LG = createField(DSL.name("lg"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.bm</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> BM = createField(DSL.name("bm"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ts</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> TS = createField(DSL.name("ts"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.cs</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> CS = createField(DSL.name("cs"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.wi</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> WI = createField(DSL.name("wi"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.sk</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> SK = createField(DSL.name("sk"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.yb</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> YB = createField(DSL.name("yb"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.rr</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> RR = createField(DSL.name("rr"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.tc</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> TC = createField(DSL.name("tc"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.sp</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> SP = createField(DSL.name("sp"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.sm</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> SM = createField(DSL.name("sm"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.tr</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> TR = createField(DSL.name("tr"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ab</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> AB = createField(DSL.name("ab"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ch</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> CH = createField(DSL.name("ch"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.tf</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> TF = createField(DSL.name("tf"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ud</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> UD = createField(DSL.name("ud"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.pd</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> PD = createField(DSL.name("pd"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ff</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> FF = createField(DSL.name("ff"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.bs</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> BS = createField(DSL.name("bs"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.dt</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> DT = createField(DSL.name("dt"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.sre</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> SRE = createField(DSL.name("sre"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.bre</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> BRE = createField(DSL.name("bre"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.nie</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> NIE = createField(DSL.name("nie"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.fre</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> FRE = createField(DSL.name("fre"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.sc</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> SC = createField(DSL.name("sc"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ml</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> ML = createField(DSL.name("ml"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.md</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> MD = createField(DSL.name("md"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ec</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> EC = createField(DSL.name("ec"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.v</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> V = createField(DSL.name("v"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.f</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> F = createField(DSL.name("f"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ea</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> EA = createField(DSL.name("ea"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.ps</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> PS = createField(DSL.name("ps"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.estado</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, String> ESTADO = createField(DSL.name("estado"), org.jooq.impl.SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.fecha_ingreso</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, LocalDateTime> FECHA_INGRESO = createField(DSL.name("fecha_ingreso"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.fecha_modifica</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, LocalDateTime> FECHA_MODIFICA = createField(DSL.name("fecha_modifica"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.usuario_ingreso</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> USUARIO_INGRESO = createField(DSL.name("usuario_ingreso"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.usuario_modifica</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Integer> USUARIO_MODIFICA = createField(DSL.name("usuario_modifica"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_cal_defecto_seleccion.id_sol_calidad</code>.
     */
    public final TableField<TabSolCalDefectoSeleccionRecord, Long> ID_SOL_CALIDAD = createField(DSL.name("id_sol_calidad"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.tab_sol_cal_defecto_seleccion</code> table reference
     */
    public TabSolCalDefectoSeleccion() {
        this(DSL.name("tab_sol_cal_defecto_seleccion"), null);
    }

    /**
     * Create an aliased <code>public.tab_sol_cal_defecto_seleccion</code> table reference
     */
    public TabSolCalDefectoSeleccion(String alias) {
        this(DSL.name(alias), TAB_SOL_CAL_DEFECTO_SELECCION);
    }

    /**
     * Create an aliased <code>public.tab_sol_cal_defecto_seleccion</code> table reference
     */
    public TabSolCalDefectoSeleccion(Name alias) {
        this(alias, TAB_SOL_CAL_DEFECTO_SELECCION);
    }

    private TabSolCalDefectoSeleccion(Name alias, Table<TabSolCalDefectoSeleccionRecord> aliased) {
        this(alias, aliased, null);
    }

    private TabSolCalDefectoSeleccion(Name alias, Table<TabSolCalDefectoSeleccionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TabSolCalDefectoSeleccion(Table<O> child, ForeignKey<O, TabSolCalDefectoSeleccionRecord> key) {
        super(child, key, TAB_SOL_CAL_DEFECTO_SELECCION);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TAB_SOL_CAL_DEFECTO_SELECCION_PKEY);
    }

    @Override
    public UniqueKey<TabSolCalDefectoSeleccionRecord> getPrimaryKey() {
        return Keys.TAB_SOL_CAL_DEFECTO_SELECCION_PKEY;
    }

    @Override
    public List<UniqueKey<TabSolCalDefectoSeleccionRecord>> getKeys() {
        return Arrays.<UniqueKey<TabSolCalDefectoSeleccionRecord>>asList(Keys.TAB_SOL_CAL_DEFECTO_SELECCION_PKEY);
    }

    @Override
    public List<ForeignKey<TabSolCalDefectoSeleccionRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TabSolCalDefectoSeleccionRecord, ?>>asList(Keys.TAB_SOL_CAL_DEFECTO_SELECCION__TAB_SOL_CAL_DEFECTO_SELECCION_USUARIO_INGRESO_FKEY, Keys.TAB_SOL_CAL_DEFECTO_SELECCION__TAB_SOL_CAL_DEFECTO_SELECCION_USUARIO_MODIFICA_FKEY, Keys.TAB_SOL_CAL_DEFECTO_SELECCION__TAB_SOL_CAL_DEFECTO_SELECCION_ID_SOL_CALIDAD_FKEY);
    }

    public TabUsuario tabSolCalDefectoSeleccion_TabSolCalDefectoSeleccionUsuarioIngresoFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_CAL_DEFECTO_SELECCION__TAB_SOL_CAL_DEFECTO_SELECCION_USUARIO_INGRESO_FKEY);
    }

    public TabUsuario tabSolCalDefectoSeleccion_TabSolCalDefectoSeleccionUsuarioModificaFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_CAL_DEFECTO_SELECCION__TAB_SOL_CAL_DEFECTO_SELECCION_USUARIO_MODIFICA_FKEY);
    }

    public TabSolCalidad tabSolCalidad() {
        return new TabSolCalidad(this, Keys.TAB_SOL_CAL_DEFECTO_SELECCION__TAB_SOL_CAL_DEFECTO_SELECCION_ID_SOL_CALIDAD_FKEY);
    }

    @Override
    public TabSolCalDefectoSeleccion as(String alias) {
        return new TabSolCalDefectoSeleccion(DSL.name(alias), this);
    }

    @Override
    public TabSolCalDefectoSeleccion as(Name alias) {
        return new TabSolCalDefectoSeleccion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolCalDefectoSeleccion rename(String name) {
        return new TabSolCalDefectoSeleccion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolCalDefectoSeleccion rename(Name name) {
        return new TabSolCalDefectoSeleccion(name, null);
    }
}
