/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables;


import com.inspector.ws.db.schema.Indexes;
import com.inspector.ws.db.schema.Keys;
import com.inspector.ws.db.schema.Public;
import com.inspector.ws.db.schema.tables.records.TabSolCalLargoDedoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolCalLargoDedo extends TableImpl<TabSolCalLargoDedoRecord> {

    private static final long serialVersionUID = -569567510;

    /**
     * The reference instance of <code>public.tab_sol_cal_largo_dedo</code>
     */
    public static final TabSolCalLargoDedo TAB_SOL_CAL_LARGO_DEDO = new TabSolCalLargoDedo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TabSolCalLargoDedoRecord> getRecordType() {
        return TabSolCalLargoDedoRecord.class;
    }

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.id_sol_cal_largo_dedo</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Long> ID_SOL_CAL_LARGO_DEDO = createField(DSL.name("id_sol_cal_largo_dedo"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar80</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR80 = createField(DSL.name("lar80"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar82</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR82 = createField(DSL.name("lar82"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar84</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR84 = createField(DSL.name("lar84"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar86</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR86 = createField(DSL.name("lar86"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar88</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR88 = createField(DSL.name("lar88"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar90</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR90 = createField(DSL.name("lar90"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar92</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR92 = createField(DSL.name("lar92"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar94</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR94 = createField(DSL.name("lar94"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar96</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR96 = createField(DSL.name("lar96"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar98</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR98 = createField(DSL.name("lar98"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar100</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR100 = createField(DSL.name("lar100"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar102</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR102 = createField(DSL.name("lar102"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar104</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR104 = createField(DSL.name("lar104"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar106</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR106 = createField(DSL.name("lar106"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar108</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR108 = createField(DSL.name("lar108"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar110</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR110 = createField(DSL.name("lar110"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar112</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR112 = createField(DSL.name("lar112"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar114</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR114 = createField(DSL.name("lar114"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar116</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR116 = createField(DSL.name("lar116"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar118</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR118 = createField(DSL.name("lar118"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.estado</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, String> ESTADO = createField(DSL.name("estado"), org.jooq.impl.SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.fecha_ingreso</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, LocalDateTime> FECHA_INGRESO = createField(DSL.name("fecha_ingreso"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.fecha_modifica</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, LocalDateTime> FECHA_MODIFICA = createField(DSL.name("fecha_modifica"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.usuario_ingreso</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> USUARIO_INGRESO = createField(DSL.name("usuario_ingreso"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.usuario_modifica</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> USUARIO_MODIFICA = createField(DSL.name("usuario_modifica"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.id_sol_calidad</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Long> ID_SOL_CALIDAD = createField(DSL.name("id_sol_calidad"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.tab_sol_cal_largo_dedo</code> table reference
     */
    public TabSolCalLargoDedo() {
        this(DSL.name("tab_sol_cal_largo_dedo"), null);
    }

    /**
     * Create an aliased <code>public.tab_sol_cal_largo_dedo</code> table reference
     */
    public TabSolCalLargoDedo(String alias) {
        this(DSL.name(alias), TAB_SOL_CAL_LARGO_DEDO);
    }

    /**
     * Create an aliased <code>public.tab_sol_cal_largo_dedo</code> table reference
     */
    public TabSolCalLargoDedo(Name alias) {
        this(alias, TAB_SOL_CAL_LARGO_DEDO);
    }

    private TabSolCalLargoDedo(Name alias, Table<TabSolCalLargoDedoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TabSolCalLargoDedo(Name alias, Table<TabSolCalLargoDedoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TabSolCalLargoDedo(Table<O> child, ForeignKey<O, TabSolCalLargoDedoRecord> key) {
        super(child, key, TAB_SOL_CAL_LARGO_DEDO);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TAB_SOL_CAL_LARGO_DEDO_PKEY);
    }

    @Override
    public UniqueKey<TabSolCalLargoDedoRecord> getPrimaryKey() {
        return Keys.TAB_SOL_CAL_LARGO_DEDO_PKEY;
    }

    @Override
    public List<UniqueKey<TabSolCalLargoDedoRecord>> getKeys() {
        return Arrays.<UniqueKey<TabSolCalLargoDedoRecord>>asList(Keys.TAB_SOL_CAL_LARGO_DEDO_PKEY);
    }

    @Override
    public List<ForeignKey<TabSolCalLargoDedoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TabSolCalLargoDedoRecord, ?>>asList(Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_USUARIO_INGRESO_FKEY, Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_USUARIO_MODIFICA_FKEY, Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_ID_SOL_CALIDAD_FKEY);
    }

    public TabUsuario tabSolCalLargoDedo_TabSolCalLargoDedoUsuarioIngresoFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_USUARIO_INGRESO_FKEY);
    }

    public TabUsuario tabSolCalLargoDedo_TabSolCalLargoDedoUsuarioModificaFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_USUARIO_MODIFICA_FKEY);
    }

    public TabSolCalidad tabSolCalidad() {
        return new TabSolCalidad(this, Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_ID_SOL_CALIDAD_FKEY);
    }

    @Override
    public TabSolCalLargoDedo as(String alias) {
        return new TabSolCalLargoDedo(DSL.name(alias), this);
    }

    @Override
    public TabSolCalLargoDedo as(Name alias) {
        return new TabSolCalLargoDedo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolCalLargoDedo rename(String name) {
        return new TabSolCalLargoDedo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolCalLargoDedo rename(Name name) {
        return new TabSolCalLargoDedo(name, null);
    }
}
