/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables;


import com.inspector.ws.db.schema.Indexes;
import com.inspector.ws.db.schema.Keys;
import com.inspector.ws.db.schema.Public;
import com.inspector.ws.db.schema.tables.records.TabSolCalPesoClusterRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolCalPesoCluster extends TableImpl<TabSolCalPesoClusterRecord> {

    private static final long serialVersionUID = -1585628392;

    /**
     * The reference instance of <code>public.tab_sol_cal_peso_cluster</code>
     */
    public static final TabSolCalPesoCluster TAB_SOL_CAL_PESO_CLUSTER = new TabSolCalPesoCluster();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TabSolCalPesoClusterRecord> getRecordType() {
        return TabSolCalPesoClusterRecord.class;
    }

    /**
     * The column <code>public.tab_sol_cal_peso_cluster.id_sol_cal_peso_cluster</code>.
     */
    public final TableField<TabSolCalPesoClusterRecord, Long> ID_SOL_CAL_PESO_CLUSTER = createField(DSL.name("id_sol_cal_peso_cluster"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tab_sol_cal_peso_cluster.numero</code>.
     */
    public final TableField<TabSolCalPesoClusterRecord, Integer> NUMERO = createField(DSL.name("numero"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_peso_cluster.peso</code>.
     */
    public final TableField<TabSolCalPesoClusterRecord, Float> PESO = createField(DSL.name("peso"), org.jooq.impl.SQLDataType.REAL.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.REAL)), this, "");

    /**
     * The column <code>public.tab_sol_cal_peso_cluster.fecha_ingreso</code>.
     */
    public final TableField<TabSolCalPesoClusterRecord, LocalDateTime> FECHA_INGRESO = createField(DSL.name("fecha_ingreso"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_cal_peso_cluster.fecha_modifica</code>.
     */
    public final TableField<TabSolCalPesoClusterRecord, LocalDateTime> FECHA_MODIFICA = createField(DSL.name("fecha_modifica"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_cal_peso_cluster.usuario_ingreso</code>.
     */
    public final TableField<TabSolCalPesoClusterRecord, Integer> USUARIO_INGRESO = createField(DSL.name("usuario_ingreso"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_cal_peso_cluster.usuario_modifica</code>.
     */
    public final TableField<TabSolCalPesoClusterRecord, Integer> USUARIO_MODIFICA = createField(DSL.name("usuario_modifica"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_cal_peso_cluster.id_sol_calidad</code>.
     */
    public final TableField<TabSolCalPesoClusterRecord, Long> ID_SOL_CALIDAD = createField(DSL.name("id_sol_calidad"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.tab_sol_cal_peso_cluster</code> table reference
     */
    public TabSolCalPesoCluster() {
        this(DSL.name("tab_sol_cal_peso_cluster"), null);
    }

    /**
     * Create an aliased <code>public.tab_sol_cal_peso_cluster</code> table reference
     */
    public TabSolCalPesoCluster(String alias) {
        this(DSL.name(alias), TAB_SOL_CAL_PESO_CLUSTER);
    }

    /**
     * Create an aliased <code>public.tab_sol_cal_peso_cluster</code> table reference
     */
    public TabSolCalPesoCluster(Name alias) {
        this(alias, TAB_SOL_CAL_PESO_CLUSTER);
    }

    private TabSolCalPesoCluster(Name alias, Table<TabSolCalPesoClusterRecord> aliased) {
        this(alias, aliased, null);
    }

    private TabSolCalPesoCluster(Name alias, Table<TabSolCalPesoClusterRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TabSolCalPesoCluster(Table<O> child, ForeignKey<O, TabSolCalPesoClusterRecord> key) {
        super(child, key, TAB_SOL_CAL_PESO_CLUSTER);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TAB_SOL_CAL_PESO_CLUSTER_PKEY);
    }

    @Override
    public UniqueKey<TabSolCalPesoClusterRecord> getPrimaryKey() {
        return Keys.TAB_SOL_CAL_PESO_CLUSTER_PKEY;
    }

    @Override
    public List<UniqueKey<TabSolCalPesoClusterRecord>> getKeys() {
        return Arrays.<UniqueKey<TabSolCalPesoClusterRecord>>asList(Keys.TAB_SOL_CAL_PESO_CLUSTER_PKEY);
    }

    @Override
    public List<ForeignKey<TabSolCalPesoClusterRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TabSolCalPesoClusterRecord, ?>>asList(Keys.TAB_SOL_CAL_PESO_CLUSTER__TAB_SOL_CAL_PESO_CLUSTER_USUARIO_INGRESO_FKEY, Keys.TAB_SOL_CAL_PESO_CLUSTER__TAB_SOL_CAL_PESO_CLUSTER_USUARIO_MODIFICA_FKEY, Keys.TAB_SOL_CAL_PESO_CLUSTER__TAB_SOL_CAL_PESO_CLUSTER_ID_SOL_CALIDAD_FKEY);
    }

    public TabUsuario tabSolCalPesoCluster_TabSolCalPesoClusterUsuarioIngresoFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_CAL_PESO_CLUSTER__TAB_SOL_CAL_PESO_CLUSTER_USUARIO_INGRESO_FKEY);
    }

    public TabUsuario tabSolCalPesoCluster_TabSolCalPesoClusterUsuarioModificaFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_CAL_PESO_CLUSTER__TAB_SOL_CAL_PESO_CLUSTER_USUARIO_MODIFICA_FKEY);
    }

    public TabSolCalidad tabSolCalidad() {
        return new TabSolCalidad(this, Keys.TAB_SOL_CAL_PESO_CLUSTER__TAB_SOL_CAL_PESO_CLUSTER_ID_SOL_CALIDAD_FKEY);
    }

    @Override
    public TabSolCalPesoCluster as(String alias) {
        return new TabSolCalPesoCluster(DSL.name(alias), this);
    }

    @Override
    public TabSolCalPesoCluster as(Name alias) {
        return new TabSolCalPesoCluster(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolCalPesoCluster rename(String name) {
        return new TabSolCalPesoCluster(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolCalPesoCluster rename(Name name) {
        return new TabSolCalPesoCluster(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Integer, Float, LocalDateTime, LocalDateTime, Integer, Integer, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
