/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables;


import com.inspector.ws.db.schema.Indexes;
import com.inspector.ws.db.schema.Keys;
import com.inspector.ws.db.schema.Public;
import com.inspector.ws.db.schema.tables.records.TabSolicitudRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolicitud extends TableImpl<TabSolicitudRecord> {

    private static final long serialVersionUID = -80561017;

    /**
     * The reference instance of <code>public.tab_solicitud</code>
     */
    public static final TabSolicitud TAB_SOLICITUD = new TabSolicitud();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TabSolicitudRecord> getRecordType() {
        return TabSolicitudRecord.class;
    }

    /**
     * The column <code>public.tab_solicitud.id_solicitud</code>.
     */
    public final TableField<TabSolicitudRecord, Long> ID_SOLICITUD = createField(DSL.name("id_solicitud"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tab_solicitud.nro_semana</code>.
     */
    public final TableField<TabSolicitudRecord, Integer> NRO_SEMANA = createField(DSL.name("nro_semana"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_solicitud.exportador</code>.
     */
    public final TableField<TabSolicitudRecord, String> EXPORTADOR = createField(DSL.name("exportador"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.cliente</code>.
     */
    public final TableField<TabSolicitudRecord, String> CLIENTE = createField(DSL.name("cliente"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.tipo_solicitud</code>.
     */
    public final TableField<TabSolicitudRecord, String> TIPO_SOLICITUD = createField(DSL.name("tipo_solicitud"), org.jooq.impl.SQLDataType.VARCHAR(3).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.productor</code>.
     */
    public final TableField<TabSolicitudRecord, String> PRODUCTOR = createField(DSL.name("productor"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.cod_productor</code>.
     */
    public final TableField<TabSolicitudRecord, String> COD_PRODUCTOR = createField(DSL.name("cod_productor"), org.jooq.impl.SQLDataType.VARCHAR(20).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.cod_magap</code>.
     */
    public final TableField<TabSolicitudRecord, String> COD_MAGAP = createField(DSL.name("cod_magap"), org.jooq.impl.SQLDataType.VARCHAR(20).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.puerto_embarque</code>.
     */
    public final TableField<TabSolicitudRecord, String> PUERTO_EMBARQUE = createField(DSL.name("puerto_embarque"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.zona</code>.
     */
    public final TableField<TabSolicitudRecord, String> ZONA = createField(DSL.name("zona"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.fecha_inicio</code>.
     */
    public final TableField<TabSolicitudRecord, LocalDateTime> FECHA_INICIO = createField(DSL.name("fecha_inicio"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_solicitud.fecha_termino</code>.
     */
    public final TableField<TabSolicitudRecord, LocalDateTime> FECHA_TERMINO = createField(DSL.name("fecha_termino"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_solicitud.contenedor</code>.
     */
    public final TableField<TabSolicitudRecord, String> CONTENEDOR = createField(DSL.name("contenedor"), org.jooq.impl.SQLDataType.VARCHAR(5).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.observacion</code>.
     */
    public final TableField<TabSolicitudRecord, String> OBSERVACION = createField(DSL.name("observacion"), org.jooq.impl.SQLDataType.VARCHAR(1000).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.estado</code>.
     */
    public final TableField<TabSolicitudRecord, String> ESTADO = createField(DSL.name("estado"), org.jooq.impl.SQLDataType.VARCHAR(3), this, "");

    /**
     * The column <code>public.tab_solicitud.fecha_ingreso</code>.
     */
    public final TableField<TabSolicitudRecord, LocalDateTime> FECHA_INGRESO = createField(DSL.name("fecha_ingreso"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_solicitud.fecha_modifica</code>.
     */
    public final TableField<TabSolicitudRecord, LocalDateTime> FECHA_MODIFICA = createField(DSL.name("fecha_modifica"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_solicitud.usuario_ingreso</code>.
     */
    public final TableField<TabSolicitudRecord, Integer> USUARIO_INGRESO = createField(DSL.name("usuario_ingreso"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_solicitud.usuario_modifica</code>.
     */
    public final TableField<TabSolicitudRecord, Integer> USUARIO_MODIFICA = createField(DSL.name("usuario_modifica"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_solicitud.nom_evaluador_01</code>.
     */
    public final TableField<TabSolicitudRecord, String> NOM_EVALUADOR_01 = createField(DSL.name("nom_evaluador_01"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.ci_evaluador_01</code>.
     */
    public final TableField<TabSolicitudRecord, String> CI_EVALUADOR_01 = createField(DSL.name("ci_evaluador_01"), org.jooq.impl.SQLDataType.VARCHAR(20).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.nom_evaluador_02</code>.
     */
    public final TableField<TabSolicitudRecord, String> NOM_EVALUADOR_02 = createField(DSL.name("nom_evaluador_02"), org.jooq.impl.SQLDataType.VARCHAR(100).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>public.tab_solicitud.ci_evaluador_02</code>.
     */
    public final TableField<TabSolicitudRecord, String> CI_EVALUADOR_02 = createField(DSL.name("ci_evaluador_02"), org.jooq.impl.SQLDataType.VARCHAR(20).defaultValue(org.jooq.impl.DSL.field("''::character varying", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * Create a <code>public.tab_solicitud</code> table reference
     */
    public TabSolicitud() {
        this(DSL.name("tab_solicitud"), null);
    }

    /**
     * Create an aliased <code>public.tab_solicitud</code> table reference
     */
    public TabSolicitud(String alias) {
        this(DSL.name(alias), TAB_SOLICITUD);
    }

    /**
     * Create an aliased <code>public.tab_solicitud</code> table reference
     */
    public TabSolicitud(Name alias) {
        this(alias, TAB_SOLICITUD);
    }

    private TabSolicitud(Name alias, Table<TabSolicitudRecord> aliased) {
        this(alias, aliased, null);
    }

    private TabSolicitud(Name alias, Table<TabSolicitudRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TabSolicitud(Table<O> child, ForeignKey<O, TabSolicitudRecord> key) {
        super(child, key, TAB_SOLICITUD);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TAB_SOLICITUD_PKEY);
    }

    @Override
    public UniqueKey<TabSolicitudRecord> getPrimaryKey() {
        return Keys.TAB_SOLICITUD_PKEY;
    }

    @Override
    public List<UniqueKey<TabSolicitudRecord>> getKeys() {
        return Arrays.<UniqueKey<TabSolicitudRecord>>asList(Keys.TAB_SOLICITUD_PKEY);
    }

    @Override
    public List<ForeignKey<TabSolicitudRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TabSolicitudRecord, ?>>asList(Keys.TAB_SOLICITUD__TAB_SOLICITUD_USUARIO_INGRESO_FKEY, Keys.TAB_SOLICITUD__TAB_SOLICITUD_USUARIO_MODIFICA_FKEY);
    }

    public TabUsuario tabSolicitud_TabSolicitudUsuarioIngresoFkey() {
        return new TabUsuario(this, Keys.TAB_SOLICITUD__TAB_SOLICITUD_USUARIO_INGRESO_FKEY);
    }

    public TabUsuario tabSolicitud_TabSolicitudUsuarioModificaFkey() {
        return new TabUsuario(this, Keys.TAB_SOLICITUD__TAB_SOLICITUD_USUARIO_MODIFICA_FKEY);
    }

    @Override
    public TabSolicitud as(String alias) {
        return new TabSolicitud(DSL.name(alias), this);
    }

    @Override
    public TabSolicitud as(Name alias) {
        return new TabSolicitud(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolicitud rename(String name) {
        return new TabSolicitud(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolicitud rename(Name name) {
        return new TabSolicitud(name, null);
    }
}
