/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables;


import com.inspector.ws.db.schema.Indexes;
import com.inspector.ws.db.schema.Keys;
import com.inspector.ws.db.schema.Public;
import com.inspector.ws.db.schema.tables.records.TabSolCalLargoDedoRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolCalLargoDedo extends TableImpl<TabSolCalLargoDedoRecord> {

    private static final long serialVersionUID = 917919654;

    /**
     * The reference instance of <code>public.tab_sol_cal_largo_dedo</code>
     */
    public static final TabSolCalLargoDedo TAB_SOL_CAL_LARGO_DEDO = new TabSolCalLargoDedo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TabSolCalLargoDedoRecord> getRecordType() {
        return TabSolCalLargoDedoRecord.class;
    }

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.id_sol_cal_largo_dedo</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Long> ID_SOL_CAL_LARGO_DEDO = createField(DSL.name("id_sol_cal_largo_dedo"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_80</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_80 = createField(DSL.name("lar_80"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_82</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_82 = createField(DSL.name("lar_82"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_84</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_84 = createField(DSL.name("lar_84"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_86</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_86 = createField(DSL.name("lar_86"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_88</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_88 = createField(DSL.name("lar_88"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_90</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_90 = createField(DSL.name("lar_90"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_92</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_92 = createField(DSL.name("lar_92"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_94</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_94 = createField(DSL.name("lar_94"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_96</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_96 = createField(DSL.name("lar_96"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_98</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_98 = createField(DSL.name("lar_98"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_100</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_100 = createField(DSL.name("lar_100"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_102</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_102 = createField(DSL.name("lar_102"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_104</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_104 = createField(DSL.name("lar_104"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_106</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_106 = createField(DSL.name("lar_106"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_108</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_108 = createField(DSL.name("lar_108"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_110</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_110 = createField(DSL.name("lar_110"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_112</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_112 = createField(DSL.name("lar_112"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_114</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_114 = createField(DSL.name("lar_114"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_116</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_116 = createField(DSL.name("lar_116"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.lar_118</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> LAR_118 = createField(DSL.name("lar_118"), org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.field("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.estado</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, String> ESTADO = createField(DSL.name("estado"), org.jooq.impl.SQLDataType.VARCHAR(1), this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.fecha_ingreso</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, LocalDateTime> FECHA_INGRESO = createField(DSL.name("fecha_ingreso"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.fecha_modifica</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, LocalDateTime> FECHA_MODIFICA = createField(DSL.name("fecha_modifica"), org.jooq.impl.SQLDataType.LOCALDATETIME, this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.usuario_ingreso</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> USUARIO_INGRESO = createField(DSL.name("usuario_ingreso"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.usuario_modifica</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Integer> USUARIO_MODIFICA = createField(DSL.name("usuario_modifica"), org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.tab_sol_cal_largo_dedo.id_sol_calidad</code>.
     */
    public final TableField<TabSolCalLargoDedoRecord, Long> ID_SOL_CALIDAD = createField(DSL.name("id_sol_calidad"), org.jooq.impl.SQLDataType.BIGINT, this, "");

    /**
     * Create a <code>public.tab_sol_cal_largo_dedo</code> table reference
     */
    public TabSolCalLargoDedo() {
        this(DSL.name("tab_sol_cal_largo_dedo"), null);
    }

    /**
     * Create an aliased <code>public.tab_sol_cal_largo_dedo</code> table reference
     */
    public TabSolCalLargoDedo(String alias) {
        this(DSL.name(alias), TAB_SOL_CAL_LARGO_DEDO);
    }

    /**
     * Create an aliased <code>public.tab_sol_cal_largo_dedo</code> table reference
     */
    public TabSolCalLargoDedo(Name alias) {
        this(alias, TAB_SOL_CAL_LARGO_DEDO);
    }

    private TabSolCalLargoDedo(Name alias, Table<TabSolCalLargoDedoRecord> aliased) {
        this(alias, aliased, null);
    }

    private TabSolCalLargoDedo(Name alias, Table<TabSolCalLargoDedoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TabSolCalLargoDedo(Table<O> child, ForeignKey<O, TabSolCalLargoDedoRecord> key) {
        super(child, key, TAB_SOL_CAL_LARGO_DEDO);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TAB_SOL_CAL_LARGO_DEDO_PKEY);
    }

    @Override
    public UniqueKey<TabSolCalLargoDedoRecord> getPrimaryKey() {
        return Keys.TAB_SOL_CAL_LARGO_DEDO_PKEY;
    }

    @Override
    public List<UniqueKey<TabSolCalLargoDedoRecord>> getKeys() {
        return Arrays.<UniqueKey<TabSolCalLargoDedoRecord>>asList(Keys.TAB_SOL_CAL_LARGO_DEDO_PKEY);
    }

    @Override
    public List<ForeignKey<TabSolCalLargoDedoRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TabSolCalLargoDedoRecord, ?>>asList(Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_USUARIO_INGRESO_FKEY, Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_USUARIO_MODIFICA_FKEY, Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_ID_SOL_CALIDAD_FKEY);
    }

    public TabUsuario tabSolCalLargoDedo_TabSolCalLargoDedoUsuarioIngresoFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_USUARIO_INGRESO_FKEY);
    }

    public TabUsuario tabSolCalLargoDedo_TabSolCalLargoDedoUsuarioModificaFkey() {
        return new TabUsuario(this, Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_USUARIO_MODIFICA_FKEY);
    }

    public TabSolCalidad tabSolCalidad() {
        return new TabSolCalidad(this, Keys.TAB_SOL_CAL_LARGO_DEDO__TAB_SOL_CAL_LARGO_DEDO_ID_SOL_CALIDAD_FKEY);
    }

    @Override
    public TabSolCalLargoDedo as(String alias) {
        return new TabSolCalLargoDedo(DSL.name(alias), this);
    }

    @Override
    public TabSolCalLargoDedo as(Name alias) {
        return new TabSolCalLargoDedo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolCalLargoDedo rename(String name) {
        return new TabSolCalLargoDedo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TabSolCalLargoDedo rename(Name name) {
        return new TabSolCalLargoDedo(name, null);
    }
}
