/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema;


import javax.annotation.processing.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.sec_sol_cal_calibre</code>
     */
    public static final Sequence<Long> SEC_SOL_CAL_CALIBRE = new SequenceImpl<Long>("sec_sol_cal_calibre", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_cal_largo_dedo</code>
     */
    public static final Sequence<Long> SEC_SOL_CAL_LARGO_DEDO = new SequenceImpl<Long>("sec_sol_cal_largo_dedo", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_cal_packing_list</code>
     */
    public static final Sequence<Long> SEC_SOL_CAL_PACKING_LIST = new SequenceImpl<Long>("sec_sol_cal_packing_list", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_cal_peso_cluster</code>
     */
    public static final Sequence<Long> SEC_SOL_CAL_PESO_CLUSTER = new SequenceImpl<Long>("sec_sol_cal_peso_cluster", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_calibracion_fruta</code>
     */
    public static final Sequence<Long> SEC_SOL_CALIBRACION_FRUTA = new SequenceImpl<Long>("sec_sol_calibracion_fruta", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_calidad</code>
     */
    public static final Sequence<Long> SEC_SOL_CALIDAD = new SequenceImpl<Long>("sec_sol_calidad", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_con_calibracion_fruta</code>
     */
    public static final Sequence<Long> SEC_SOL_CON_CALIBRACION_FRUTA = new SequenceImpl<Long>("sec_sol_con_calibracion_fruta", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_consolidacion_gancho</code>
     */
    public static final Sequence<Long> SEC_SOL_CONSOLIDACION_GANCHO = new SequenceImpl<Long>("sec_sol_consolidacion_gancho", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_consolidado_gancho</code>
     */
    public static final Sequence<Long> SEC_SOL_CONSOLIDADO_GANCHO = new SequenceImpl<Long>("sec_sol_consolidado_gancho", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_contenedor</code>
     */
    public static final Sequence<Long> SEC_SOL_CONTENEDOR = new SequenceImpl<Long>("sec_sol_contenedor", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_control_peso</code>
     */
    public static final Sequence<Long> SEC_SOL_CONTROL_PESO = new SequenceImpl<Long>("sec_sol_control_peso", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_defecto_seleccion</code>
     */
    public static final Sequence<Long> SEC_SOL_DEFECTO_SELECCION = new SequenceImpl<Long>("sec_sol_defecto_seleccion", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_finca</code>
     */
    public static final Sequence<Long> SEC_SOL_FINCA = new SequenceImpl<Long>("sec_sol_finca", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_imagen</code>
     */
    public static final Sequence<Long> SEC_SOL_IMAGEN = new SequenceImpl<Long>("sec_sol_imagen", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_proceso</code>
     */
    public static final Sequence<Long> SEC_SOL_PROCESO = new SequenceImpl<Long>("sec_sol_proceso", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_sello_instalado</code>
     */
    public static final Sequence<Long> SEC_SOL_SELLO_INSTALADO = new SequenceImpl<Long>("sec_sol_sello_instalado", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_sello_llegada</code>
     */
    public static final Sequence<Long> SEC_SOL_SELLO_LLEGADA = new SequenceImpl<Long>("sec_sol_sello_llegada", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_sol_transportista</code>
     */
    public static final Sequence<Long> SEC_SOL_TRANSPORTISTA = new SequenceImpl<Long>("sec_sol_transportista", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));

    /**
     * The sequence <code>public.sec_solicitud</code>
     */
    public static final Sequence<Long> SEC_SOLICITUD = new SequenceImpl<Long>("sec_solicitud", Public.PUBLIC, org.jooq.impl.SQLDataType.BIGINT.nullable(false));
}
