/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolCalCalibre;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolCalCalibreRecord extends UpdatableRecordImpl<TabSolCalCalibreRecord> {

    private static final long serialVersionUID = -1387259859;

    /**
     * Setter for <code>public.tab_sol_cal_calibre.id_sol_cal_calibre</code>.
     */
    public void setIdSolCalCalibre(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.id_sol_cal_calibre</code>.
     */
    public Long getIdSolCalCalibre() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_ug</code>.
     */
    public void setCalUg(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_ug</code>.
     */
    public Integer getCalUg() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_og</code>.
     */
    public void setCalOg(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_og</code>.
     */
    public Integer getCalOg() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal37</code>.
     */
    public void setCal37(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal37</code>.
     */
    public Integer getCal37() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal38</code>.
     */
    public void setCal38(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal38</code>.
     */
    public Integer getCal38() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal39</code>.
     */
    public void setCal39(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal39</code>.
     */
    public Integer getCal39() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal40</code>.
     */
    public void setCal40(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal40</code>.
     */
    public Integer getCal40() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal41</code>.
     */
    public void setCal41(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal41</code>.
     */
    public Integer getCal41() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal42</code>.
     */
    public void setCal42(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal42</code>.
     */
    public Integer getCal42() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal43</code>.
     */
    public void setCal43(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal43</code>.
     */
    public Integer getCal43() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal44</code>.
     */
    public void setCal44(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal44</code>.
     */
    public Integer getCal44() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal45</code>.
     */
    public void setCal45(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal45</code>.
     */
    public Integer getCal45() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal46</code>.
     */
    public void setCal46(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal46</code>.
     */
    public Integer getCal46() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal47</code>.
     */
    public void setCal47(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal47</code>.
     */
    public Integer getCal47() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal48</code>.
     */
    public void setCal48(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal48</code>.
     */
    public Integer getCal48() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal49</code>.
     */
    public void setCal49(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal49</code>.
     */
    public Integer getCal49() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal50</code>.
     */
    public void setCal50(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal50</code>.
     */
    public Integer getCal50() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal51</code>.
     */
    public void setCal51(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal51</code>.
     */
    public Integer getCal51() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal52</code>.
     */
    public void setCal52(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal52</code>.
     */
    public Integer getCal52() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal53</code>.
     */
    public void setCal53(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal53</code>.
     */
    public Integer getCal53() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal54</code>.
     */
    public void setCal54(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal54</code>.
     */
    public Integer getCal54() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.estado</code>.
     */
    public void setEstado(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.estado</code>.
     */
    public String getEstado() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(22);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(25);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.id_sol_calidad</code>.
     */
    public void setIdSolCalidad(Long value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.id_sol_calidad</code>.
     */
    public Long getIdSolCalidad() {
        return (Long) get(26);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolCalCalibreRecord
     */
    public TabSolCalCalibreRecord() {
        super(TabSolCalCalibre.TAB_SOL_CAL_CALIBRE);
    }

    /**
     * Create a detached, initialised TabSolCalCalibreRecord
     */
    public TabSolCalCalibreRecord(Long idSolCalCalibre, Integer calUg, Integer calOg, Integer cal37, Integer cal38, Integer cal39, Integer cal40, Integer cal41, Integer cal42, Integer cal43, Integer cal44, Integer cal45, Integer cal46, Integer cal47, Integer cal48, Integer cal49, Integer cal50, Integer cal51, Integer cal52, Integer cal53, Integer cal54, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, Long idSolCalidad) {
        super(TabSolCalCalibre.TAB_SOL_CAL_CALIBRE);

        set(0, idSolCalCalibre);
        set(1, calUg);
        set(2, calOg);
        set(3, cal37);
        set(4, cal38);
        set(5, cal39);
        set(6, cal40);
        set(7, cal41);
        set(8, cal42);
        set(9, cal43);
        set(10, cal44);
        set(11, cal45);
        set(12, cal46);
        set(13, cal47);
        set(14, cal48);
        set(15, cal49);
        set(16, cal50);
        set(17, cal51);
        set(18, cal52);
        set(19, cal53);
        set(20, cal54);
        set(21, estado);
        set(22, fechaIngreso);
        set(23, fechaModifica);
        set(24, usuarioIngreso);
        set(25, usuarioModifica);
        set(26, idSolCalidad);
    }
}
