/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolSelloInstalado;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record19;
import org.jooq.Row19;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolSelloInstaladoRecord extends UpdatableRecordImpl<TabSolSelloInstaladoRecord> implements Record19<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long> {

    private static final long serialVersionUID = -72172266;

    /**
     * Setter for <code>public.tab_sol_sello_instalado.id_sol_sello_instalado</code>.
     */
    public void setIdSolSelloInstalado(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.id_sol_sello_instalado</code>.
     */
    public Long getIdSolSelloInstalado() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.candado_naviera</code>.
     */
    public void setCandadoNaviera(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.candado_naviera</code>.
     */
    public String getCandadoNaviera() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.sello_verificadora</code>.
     */
    public void setSelloVerificadora(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.sello_verificadora</code>.
     */
    public String getSelloVerificadora() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.cable_naviera</code>.
     */
    public void setCableNaviera(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.cable_naviera</code>.
     */
    public String getCableNaviera() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.cable_exportadora</code>.
     */
    public void setCableExportadora(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.cable_exportadora</code>.
     */
    public String getCableExportadora() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.sticker_exportadora</code>.
     */
    public void setStickerExportadora(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.sticker_exportadora</code>.
     */
    public String getStickerExportadora() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.rastreo</code>.
     */
    public void setRastreo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.rastreo</code>.
     */
    public String getRastreo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.termografo1</code>.
     */
    public void setTermografo1(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.termografo1</code>.
     */
    public String getTermografo1() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.ubicacion1</code>.
     */
    public void setUbicacion1(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.ubicacion1</code>.
     */
    public String getUbicacion1() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.termografo2</code>.
     */
    public void setTermografo2(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.termografo2</code>.
     */
    public String getTermografo2() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.ubicacion2</code>.
     */
    public void setUbicacion2(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.ubicacion2</code>.
     */
    public String getUbicacion2() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.filtro_proporcionado</code>.
     */
    public void setFiltroProporcionado(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.filtro_proporcionado</code>.
     */
    public String getFiltroProporcionado() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.termoking</code>.
     */
    public void setTermoking(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.termoking</code>.
     */
    public String getTermoking() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.estado</code>.
     */
    public void setEstado(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.estado</code>.
     */
    public String getEstado() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(14);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.tab_sol_sello_instalado.id_solicitud</code>.
     */
    public void setIdSolicitud(Long value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.tab_sol_sello_instalado.id_solicitud</code>.
     */
    public Long getIdSolicitud() {
        return (Long) get(18);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record19 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row19<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long> fieldsRow() {
        return (Row19) super.fieldsRow();
    }

    @Override
    public Row19<Long, String, String, String, String, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long> valuesRow() {
        return (Row19) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.ID_SOL_SELLO_INSTALADO;
    }

    @Override
    public Field<String> field2() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.CANDADO_NAVIERA;
    }

    @Override
    public Field<String> field3() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.SELLO_VERIFICADORA;
    }

    @Override
    public Field<String> field4() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.CABLE_NAVIERA;
    }

    @Override
    public Field<String> field5() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.CABLE_EXPORTADORA;
    }

    @Override
    public Field<String> field6() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.STICKER_EXPORTADORA;
    }

    @Override
    public Field<String> field7() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.RASTREO;
    }

    @Override
    public Field<String> field8() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.TERMOGRAFO1;
    }

    @Override
    public Field<String> field9() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.UBICACION1;
    }

    @Override
    public Field<String> field10() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.TERMOGRAFO2;
    }

    @Override
    public Field<String> field11() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.UBICACION2;
    }

    @Override
    public Field<String> field12() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.FILTRO_PROPORCIONADO;
    }

    @Override
    public Field<String> field13() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.TERMOKING;
    }

    @Override
    public Field<String> field14() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.ESTADO;
    }

    @Override
    public Field<LocalDateTime> field15() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.FECHA_INGRESO;
    }

    @Override
    public Field<LocalDateTime> field16() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.FECHA_MODIFICA;
    }

    @Override
    public Field<Integer> field17() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.USUARIO_INGRESO;
    }

    @Override
    public Field<Integer> field18() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.USUARIO_MODIFICA;
    }

    @Override
    public Field<Long> field19() {
        return TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO.ID_SOLICITUD;
    }

    @Override
    public Long component1() {
        return getIdSolSelloInstalado();
    }

    @Override
    public String component2() {
        return getCandadoNaviera();
    }

    @Override
    public String component3() {
        return getSelloVerificadora();
    }

    @Override
    public String component4() {
        return getCableNaviera();
    }

    @Override
    public String component5() {
        return getCableExportadora();
    }

    @Override
    public String component6() {
        return getStickerExportadora();
    }

    @Override
    public String component7() {
        return getRastreo();
    }

    @Override
    public String component8() {
        return getTermografo1();
    }

    @Override
    public String component9() {
        return getUbicacion1();
    }

    @Override
    public String component10() {
        return getTermografo2();
    }

    @Override
    public String component11() {
        return getUbicacion2();
    }

    @Override
    public String component12() {
        return getFiltroProporcionado();
    }

    @Override
    public String component13() {
        return getTermoking();
    }

    @Override
    public String component14() {
        return getEstado();
    }

    @Override
    public LocalDateTime component15() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime component16() {
        return getFechaModifica();
    }

    @Override
    public Integer component17() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer component18() {
        return getUsuarioModifica();
    }

    @Override
    public Long component19() {
        return getIdSolicitud();
    }

    @Override
    public Long value1() {
        return getIdSolSelloInstalado();
    }

    @Override
    public String value2() {
        return getCandadoNaviera();
    }

    @Override
    public String value3() {
        return getSelloVerificadora();
    }

    @Override
    public String value4() {
        return getCableNaviera();
    }

    @Override
    public String value5() {
        return getCableExportadora();
    }

    @Override
    public String value6() {
        return getStickerExportadora();
    }

    @Override
    public String value7() {
        return getRastreo();
    }

    @Override
    public String value8() {
        return getTermografo1();
    }

    @Override
    public String value9() {
        return getUbicacion1();
    }

    @Override
    public String value10() {
        return getTermografo2();
    }

    @Override
    public String value11() {
        return getUbicacion2();
    }

    @Override
    public String value12() {
        return getFiltroProporcionado();
    }

    @Override
    public String value13() {
        return getTermoking();
    }

    @Override
    public String value14() {
        return getEstado();
    }

    @Override
    public LocalDateTime value15() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime value16() {
        return getFechaModifica();
    }

    @Override
    public Integer value17() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer value18() {
        return getUsuarioModifica();
    }

    @Override
    public Long value19() {
        return getIdSolicitud();
    }

    @Override
    public TabSolSelloInstaladoRecord value1(Long value) {
        setIdSolSelloInstalado(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value2(String value) {
        setCandadoNaviera(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value3(String value) {
        setSelloVerificadora(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value4(String value) {
        setCableNaviera(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value5(String value) {
        setCableExportadora(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value6(String value) {
        setStickerExportadora(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value7(String value) {
        setRastreo(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value8(String value) {
        setTermografo1(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value9(String value) {
        setUbicacion1(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value10(String value) {
        setTermografo2(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value11(String value) {
        setUbicacion2(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value12(String value) {
        setFiltroProporcionado(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value13(String value) {
        setTermoking(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value14(String value) {
        setEstado(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value15(LocalDateTime value) {
        setFechaIngreso(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value16(LocalDateTime value) {
        setFechaModifica(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value17(Integer value) {
        setUsuarioIngreso(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value18(Integer value) {
        setUsuarioModifica(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord value19(Long value) {
        setIdSolicitud(value);
        return this;
    }

    @Override
    public TabSolSelloInstaladoRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, LocalDateTime value15, LocalDateTime value16, Integer value17, Integer value18, Long value19) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolSelloInstaladoRecord
     */
    public TabSolSelloInstaladoRecord() {
        super(TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO);
    }

    /**
     * Create a detached, initialised TabSolSelloInstaladoRecord
     */
    public TabSolSelloInstaladoRecord(Long idSolSelloInstalado, String candadoNaviera, String selloVerificadora, String cableNaviera, String cableExportadora, String stickerExportadora, String rastreo, String termografo1, String ubicacion1, String termografo2, String ubicacion2, String filtroProporcionado, String termoking, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, Long idSolicitud) {
        super(TabSolSelloInstalado.TAB_SOL_SELLO_INSTALADO);

        set(0, idSolSelloInstalado);
        set(1, candadoNaviera);
        set(2, selloVerificadora);
        set(3, cableNaviera);
        set(4, cableExportadora);
        set(5, stickerExportadora);
        set(6, rastreo);
        set(7, termografo1);
        set(8, ubicacion1);
        set(9, termografo2);
        set(10, ubicacion2);
        set(11, filtroProporcionado);
        set(12, termoking);
        set(13, estado);
        set(14, fechaIngreso);
        set(15, fechaModifica);
        set(16, usuarioIngreso);
        set(17, usuarioModifica);
        set(18, idSolicitud);
    }
}
