/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolImagen;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolImagenRecord extends UpdatableRecordImpl<TabSolImagenRecord> implements Record11<Long, String, String, String, byte[], String, LocalDateTime, LocalDateTime, Integer, Integer, Long> {

    private static final long serialVersionUID = 458941197;

    /**
     * Setter for <code>public.tab_sol_imagen.id_sol_imagen</code>.
     */
    public void setIdSolImagen(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_sol_imagen.id_sol_imagen</code>.
     */
    public Long getIdSolImagen() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_sol_imagen.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_sol_imagen.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tab_sol_imagen.descripcion</code>.
     */
    public void setDescripcion(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_sol_imagen.descripcion</code>.
     */
    public String getDescripcion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tab_sol_imagen.seccion</code>.
     */
    public void setSeccion(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_sol_imagen.seccion</code>.
     */
    public String getSeccion() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tab_sol_imagen.imagen</code>.
     */
    public void setImagen(byte... value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_sol_imagen.imagen</code>.
     */
    public byte[] getImagen() {
        return (byte[]) get(4);
    }

    /**
     * Setter for <code>public.tab_sol_imagen.estado</code>.
     */
    public void setEstado(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_sol_imagen.estado</code>.
     */
    public String getEstado() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tab_sol_imagen.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_sol_imagen.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.tab_sol_imagen.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_sol_imagen.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.tab_sol_imagen.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tab_sol_imagen.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.tab_sol_imagen.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tab_sol_imagen.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.tab_sol_imagen.id_solicitud</code>.
     */
    public void setIdSolicitud(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tab_sol_imagen.id_solicitud</code>.
     */
    public Long getIdSolicitud() {
        return (Long) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, byte[], String, LocalDateTime, LocalDateTime, Integer, Integer, Long> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, String, byte[], String, LocalDateTime, LocalDateTime, Integer, Integer, Long> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TabSolImagen.TAB_SOL_IMAGEN.ID_SOL_IMAGEN;
    }

    @Override
    public Field<String> field2() {
        return TabSolImagen.TAB_SOL_IMAGEN.NOMBRE;
    }

    @Override
    public Field<String> field3() {
        return TabSolImagen.TAB_SOL_IMAGEN.DESCRIPCION;
    }

    @Override
    public Field<String> field4() {
        return TabSolImagen.TAB_SOL_IMAGEN.SECCION;
    }

    @Override
    public Field<byte[]> field5() {
        return TabSolImagen.TAB_SOL_IMAGEN.IMAGEN;
    }

    @Override
    public Field<String> field6() {
        return TabSolImagen.TAB_SOL_IMAGEN.ESTADO;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return TabSolImagen.TAB_SOL_IMAGEN.FECHA_INGRESO;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return TabSolImagen.TAB_SOL_IMAGEN.FECHA_MODIFICA;
    }

    @Override
    public Field<Integer> field9() {
        return TabSolImagen.TAB_SOL_IMAGEN.USUARIO_INGRESO;
    }

    @Override
    public Field<Integer> field10() {
        return TabSolImagen.TAB_SOL_IMAGEN.USUARIO_MODIFICA;
    }

    @Override
    public Field<Long> field11() {
        return TabSolImagen.TAB_SOL_IMAGEN.ID_SOLICITUD;
    }

    @Override
    public Long component1() {
        return getIdSolImagen();
    }

    @Override
    public String component2() {
        return getNombre();
    }

    @Override
    public String component3() {
        return getDescripcion();
    }

    @Override
    public String component4() {
        return getSeccion();
    }

    @Override
    public byte[] component5() {
        return getImagen();
    }

    @Override
    public String component6() {
        return getEstado();
    }

    @Override
    public LocalDateTime component7() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime component8() {
        return getFechaModifica();
    }

    @Override
    public Integer component9() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer component10() {
        return getUsuarioModifica();
    }

    @Override
    public Long component11() {
        return getIdSolicitud();
    }

    @Override
    public Long value1() {
        return getIdSolImagen();
    }

    @Override
    public String value2() {
        return getNombre();
    }

    @Override
    public String value3() {
        return getDescripcion();
    }

    @Override
    public String value4() {
        return getSeccion();
    }

    @Override
    public byte[] value5() {
        return getImagen();
    }

    @Override
    public String value6() {
        return getEstado();
    }

    @Override
    public LocalDateTime value7() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime value8() {
        return getFechaModifica();
    }

    @Override
    public Integer value9() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer value10() {
        return getUsuarioModifica();
    }

    @Override
    public Long value11() {
        return getIdSolicitud();
    }

    @Override
    public TabSolImagenRecord value1(Long value) {
        setIdSolImagen(value);
        return this;
    }

    @Override
    public TabSolImagenRecord value2(String value) {
        setNombre(value);
        return this;
    }

    @Override
    public TabSolImagenRecord value3(String value) {
        setDescripcion(value);
        return this;
    }

    @Override
    public TabSolImagenRecord value4(String value) {
        setSeccion(value);
        return this;
    }

    @Override
    public TabSolImagenRecord value5(byte... value) {
        setImagen(value);
        return this;
    }

    @Override
    public TabSolImagenRecord value6(String value) {
        setEstado(value);
        return this;
    }

    @Override
    public TabSolImagenRecord value7(LocalDateTime value) {
        setFechaIngreso(value);
        return this;
    }

    @Override
    public TabSolImagenRecord value8(LocalDateTime value) {
        setFechaModifica(value);
        return this;
    }

    @Override
    public TabSolImagenRecord value9(Integer value) {
        setUsuarioIngreso(value);
        return this;
    }

    @Override
    public TabSolImagenRecord value10(Integer value) {
        setUsuarioModifica(value);
        return this;
    }

    @Override
    public TabSolImagenRecord value11(Long value) {
        setIdSolicitud(value);
        return this;
    }

    @Override
    public TabSolImagenRecord values(Long value1, String value2, String value3, String value4, byte[] value5, String value6, LocalDateTime value7, LocalDateTime value8, Integer value9, Integer value10, Long value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolImagenRecord
     */
    public TabSolImagenRecord() {
        super(TabSolImagen.TAB_SOL_IMAGEN);
    }

    /**
     * Create a detached, initialised TabSolImagenRecord
     */
    public TabSolImagenRecord(Long idSolImagen, String nombre, String descripcion, String seccion, byte[] imagen, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, Long idSolicitud) {
        super(TabSolImagen.TAB_SOL_IMAGEN);

        set(0, idSolImagen);
        set(1, nombre);
        set(2, descripcion);
        set(3, seccion);
        set(4, imagen);
        set(5, estado);
        set(6, fechaIngreso);
        set(7, fechaModifica);
        set(8, usuarioIngreso);
        set(9, usuarioModifica);
        set(10, idSolicitud);
    }
}
