/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolControlPeso;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolControlPesoRecord extends UpdatableRecordImpl<TabSolControlPesoRecord> implements Record13<Long, String, String, String, Float, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long, Long> {

    private static final long serialVersionUID = -153570965;

    /**
     * Setter for <code>public.tab_sol_control_peso.id_sol_control_peso</code>.
     */
    public void setIdSolControlPeso(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.id_sol_control_peso</code>.
     */
    public Long getIdSolControlPeso() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.balanza_repesa</code>.
     */
    public void setBalanzaRepesa(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.balanza_repesa</code>.
     */
    public String getBalanzaRepesa() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.condicion_balanza</code>.
     */
    public void setCondicionBalanza(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.condicion_balanza</code>.
     */
    public String getCondicionBalanza() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.tipo_balanza</code>.
     */
    public void setTipoBalanza(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.tipo_balanza</code>.
     */
    public String getTipoBalanza() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.peso_neto_fruta</code>.
     */
    public void setPesoNetoFruta(Float value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.peso_neto_fruta</code>.
     */
    public Float getPesoNetoFruta() {
        return (Float) get(4);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.observacion</code>.
     */
    public void setObservacion(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.observacion</code>.
     */
    public String getObservacion() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.estado</code>.
     */
    public void setEstado(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.estado</code>.
     */
    public String getEstado() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.id_solicitud</code>.
     */
    public void setIdSolicitud(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.id_solicitud</code>.
     */
    public Long getIdSolicitud() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>public.tab_sol_control_peso.id_sol_productor</code>.
     */
    public void setIdSolProductor(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tab_sol_control_peso.id_sol_productor</code>.
     */
    public Long getIdSolProductor() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, String, String, String, Float, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, String, String, String, Float, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.ID_SOL_CONTROL_PESO;
    }

    @Override
    public Field<String> field2() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.BALANZA_REPESA;
    }

    @Override
    public Field<String> field3() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.CONDICION_BALANZA;
    }

    @Override
    public Field<String> field4() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.TIPO_BALANZA;
    }

    @Override
    public Field<Float> field5() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.PESO_NETO_FRUTA;
    }

    @Override
    public Field<String> field6() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.OBSERVACION;
    }

    @Override
    public Field<String> field7() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.ESTADO;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.FECHA_INGRESO;
    }

    @Override
    public Field<LocalDateTime> field9() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.FECHA_MODIFICA;
    }

    @Override
    public Field<Integer> field10() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.USUARIO_INGRESO;
    }

    @Override
    public Field<Integer> field11() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.USUARIO_MODIFICA;
    }

    @Override
    public Field<Long> field12() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.ID_SOLICITUD;
    }

    @Override
    public Field<Long> field13() {
        return TabSolControlPeso.TAB_SOL_CONTROL_PESO.ID_SOL_PRODUCTOR;
    }

    @Override
    public Long component1() {
        return getIdSolControlPeso();
    }

    @Override
    public String component2() {
        return getBalanzaRepesa();
    }

    @Override
    public String component3() {
        return getCondicionBalanza();
    }

    @Override
    public String component4() {
        return getTipoBalanza();
    }

    @Override
    public Float component5() {
        return getPesoNetoFruta();
    }

    @Override
    public String component6() {
        return getObservacion();
    }

    @Override
    public String component7() {
        return getEstado();
    }

    @Override
    public LocalDateTime component8() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime component9() {
        return getFechaModifica();
    }

    @Override
    public Integer component10() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer component11() {
        return getUsuarioModifica();
    }

    @Override
    public Long component12() {
        return getIdSolicitud();
    }

    @Override
    public Long component13() {
        return getIdSolProductor();
    }

    @Override
    public Long value1() {
        return getIdSolControlPeso();
    }

    @Override
    public String value2() {
        return getBalanzaRepesa();
    }

    @Override
    public String value3() {
        return getCondicionBalanza();
    }

    @Override
    public String value4() {
        return getTipoBalanza();
    }

    @Override
    public Float value5() {
        return getPesoNetoFruta();
    }

    @Override
    public String value6() {
        return getObservacion();
    }

    @Override
    public String value7() {
        return getEstado();
    }

    @Override
    public LocalDateTime value8() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime value9() {
        return getFechaModifica();
    }

    @Override
    public Integer value10() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer value11() {
        return getUsuarioModifica();
    }

    @Override
    public Long value12() {
        return getIdSolicitud();
    }

    @Override
    public Long value13() {
        return getIdSolProductor();
    }

    @Override
    public TabSolControlPesoRecord value1(Long value) {
        setIdSolControlPeso(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value2(String value) {
        setBalanzaRepesa(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value3(String value) {
        setCondicionBalanza(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value4(String value) {
        setTipoBalanza(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value5(Float value) {
        setPesoNetoFruta(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value6(String value) {
        setObservacion(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value7(String value) {
        setEstado(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value8(LocalDateTime value) {
        setFechaIngreso(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value9(LocalDateTime value) {
        setFechaModifica(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value10(Integer value) {
        setUsuarioIngreso(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value11(Integer value) {
        setUsuarioModifica(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value12(Long value) {
        setIdSolicitud(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord value13(Long value) {
        setIdSolProductor(value);
        return this;
    }

    @Override
    public TabSolControlPesoRecord values(Long value1, String value2, String value3, String value4, Float value5, String value6, String value7, LocalDateTime value8, LocalDateTime value9, Integer value10, Integer value11, Long value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolControlPesoRecord
     */
    public TabSolControlPesoRecord() {
        super(TabSolControlPeso.TAB_SOL_CONTROL_PESO);
    }

    /**
     * Create a detached, initialised TabSolControlPesoRecord
     */
    public TabSolControlPesoRecord(Long idSolControlPeso, String balanzaRepesa, String condicionBalanza, String tipoBalanza, Float pesoNetoFruta, String observacion, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, Long idSolicitud, Long idSolProductor) {
        super(TabSolControlPeso.TAB_SOL_CONTROL_PESO);

        set(0, idSolControlPeso);
        set(1, balanzaRepesa);
        set(2, condicionBalanza);
        set(3, tipoBalanza);
        set(4, pesoNetoFruta);
        set(5, observacion);
        set(6, estado);
        set(7, fechaIngreso);
        set(8, fechaModifica);
        set(9, usuarioIngreso);
        set(10, usuarioModifica);
        set(11, idSolicitud);
        set(12, idSolProductor);
    }
}
