/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolCalPesoCluster;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolCalPesoClusterRecord extends UpdatableRecordImpl<TabSolCalPesoClusterRecord> implements Record9<Long, Integer, Float, String, LocalDateTime, LocalDateTime, Integer, Integer, Long> {

    private static final long serialVersionUID = -701632073;

    /**
     * Setter for <code>public.tab_sol_cal_peso_cluster.id_sol_cal_peso_cluster</code>.
     */
    public void setIdSolCalPesoCluster(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_peso_cluster.id_sol_cal_peso_cluster</code>.
     */
    public Long getIdSolCalPesoCluster() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_sol_cal_peso_cluster.numero</code>.
     */
    public void setNumero(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_peso_cluster.numero</code>.
     */
    public Integer getNumero() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tab_sol_cal_peso_cluster.pero</code>.
     */
    public void setPero(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_peso_cluster.pero</code>.
     */
    public Float getPero() {
        return (Float) get(2);
    }

    /**
     * Setter for <code>public.tab_sol_cal_peso_cluster.estado</code>.
     */
    public void setEstado(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_peso_cluster.estado</code>.
     */
    public String getEstado() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tab_sol_cal_peso_cluster.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_peso_cluster.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.tab_sol_cal_peso_cluster.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_peso_cluster.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.tab_sol_cal_peso_cluster.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_peso_cluster.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.tab_sol_cal_peso_cluster.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_peso_cluster.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.tab_sol_cal_peso_cluster.id_sol_calidad</code>.
     */
    public void setIdSolCalidad(Long value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_peso_cluster.id_sol_calidad</code>.
     */
    public Long getIdSolCalidad() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row9<Long, Integer, Float, String, LocalDateTime, LocalDateTime, Integer, Integer, Long> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    @Override
    public Row9<Long, Integer, Float, String, LocalDateTime, LocalDateTime, Integer, Integer, Long> valuesRow() {
        return (Row9) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TabSolCalPesoCluster.TAB_SOL_CAL_PESO_CLUSTER.ID_SOL_CAL_PESO_CLUSTER;
    }

    @Override
    public Field<Integer> field2() {
        return TabSolCalPesoCluster.TAB_SOL_CAL_PESO_CLUSTER.NUMERO;
    }

    @Override
    public Field<Float> field3() {
        return TabSolCalPesoCluster.TAB_SOL_CAL_PESO_CLUSTER.PERO;
    }

    @Override
    public Field<String> field4() {
        return TabSolCalPesoCluster.TAB_SOL_CAL_PESO_CLUSTER.ESTADO;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TabSolCalPesoCluster.TAB_SOL_CAL_PESO_CLUSTER.FECHA_INGRESO;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return TabSolCalPesoCluster.TAB_SOL_CAL_PESO_CLUSTER.FECHA_MODIFICA;
    }

    @Override
    public Field<Integer> field7() {
        return TabSolCalPesoCluster.TAB_SOL_CAL_PESO_CLUSTER.USUARIO_INGRESO;
    }

    @Override
    public Field<Integer> field8() {
        return TabSolCalPesoCluster.TAB_SOL_CAL_PESO_CLUSTER.USUARIO_MODIFICA;
    }

    @Override
    public Field<Long> field9() {
        return TabSolCalPesoCluster.TAB_SOL_CAL_PESO_CLUSTER.ID_SOL_CALIDAD;
    }

    @Override
    public Long component1() {
        return getIdSolCalPesoCluster();
    }

    @Override
    public Integer component2() {
        return getNumero();
    }

    @Override
    public Float component3() {
        return getPero();
    }

    @Override
    public String component4() {
        return getEstado();
    }

    @Override
    public LocalDateTime component5() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime component6() {
        return getFechaModifica();
    }

    @Override
    public Integer component7() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer component8() {
        return getUsuarioModifica();
    }

    @Override
    public Long component9() {
        return getIdSolCalidad();
    }

    @Override
    public Long value1() {
        return getIdSolCalPesoCluster();
    }

    @Override
    public Integer value2() {
        return getNumero();
    }

    @Override
    public Float value3() {
        return getPero();
    }

    @Override
    public String value4() {
        return getEstado();
    }

    @Override
    public LocalDateTime value5() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime value6() {
        return getFechaModifica();
    }

    @Override
    public Integer value7() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer value8() {
        return getUsuarioModifica();
    }

    @Override
    public Long value9() {
        return getIdSolCalidad();
    }

    @Override
    public TabSolCalPesoClusterRecord value1(Long value) {
        setIdSolCalPesoCluster(value);
        return this;
    }

    @Override
    public TabSolCalPesoClusterRecord value2(Integer value) {
        setNumero(value);
        return this;
    }

    @Override
    public TabSolCalPesoClusterRecord value3(Float value) {
        setPero(value);
        return this;
    }

    @Override
    public TabSolCalPesoClusterRecord value4(String value) {
        setEstado(value);
        return this;
    }

    @Override
    public TabSolCalPesoClusterRecord value5(LocalDateTime value) {
        setFechaIngreso(value);
        return this;
    }

    @Override
    public TabSolCalPesoClusterRecord value6(LocalDateTime value) {
        setFechaModifica(value);
        return this;
    }

    @Override
    public TabSolCalPesoClusterRecord value7(Integer value) {
        setUsuarioIngreso(value);
        return this;
    }

    @Override
    public TabSolCalPesoClusterRecord value8(Integer value) {
        setUsuarioModifica(value);
        return this;
    }

    @Override
    public TabSolCalPesoClusterRecord value9(Long value) {
        setIdSolCalidad(value);
        return this;
    }

    @Override
    public TabSolCalPesoClusterRecord values(Long value1, Integer value2, Float value3, String value4, LocalDateTime value5, LocalDateTime value6, Integer value7, Integer value8, Long value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolCalPesoClusterRecord
     */
    public TabSolCalPesoClusterRecord() {
        super(TabSolCalPesoCluster.TAB_SOL_CAL_PESO_CLUSTER);
    }

    /**
     * Create a detached, initialised TabSolCalPesoClusterRecord
     */
    public TabSolCalPesoClusterRecord(Long idSolCalPesoCluster, Integer numero, Float pero, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, Long idSolCalidad) {
        super(TabSolCalPesoCluster.TAB_SOL_CAL_PESO_CLUSTER);

        set(0, idSolCalPesoCluster);
        set(1, numero);
        set(2, pero);
        set(3, estado);
        set(4, fechaIngreso);
        set(5, fechaModifica);
        set(6, usuarioIngreso);
        set(7, usuarioModifica);
        set(8, idSolCalidad);
    }
}
