/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolCalLargoDedo;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolCalLargoDedoRecord extends UpdatableRecordImpl<TabSolCalLargoDedoRecord> {

    private static final long serialVersionUID = -103463600;

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.id_sol_cal_largo_dedo</code>.
     */
    public void setIdSolCalLargoDedo(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.id_sol_cal_largo_dedo</code>.
     */
    public Long getIdSolCalLargoDedo() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar80</code>.
     */
    public void setLar80(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar80</code>.
     */
    public Integer getLar80() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar82</code>.
     */
    public void setLar82(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar82</code>.
     */
    public Integer getLar82() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar84</code>.
     */
    public void setLar84(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar84</code>.
     */
    public Integer getLar84() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar86</code>.
     */
    public void setLar86(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar86</code>.
     */
    public Integer getLar86() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar88</code>.
     */
    public void setLar88(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar88</code>.
     */
    public Integer getLar88() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar90</code>.
     */
    public void setLar90(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar90</code>.
     */
    public Integer getLar90() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar92</code>.
     */
    public void setLar92(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar92</code>.
     */
    public Integer getLar92() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar94</code>.
     */
    public void setLar94(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar94</code>.
     */
    public Integer getLar94() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar96</code>.
     */
    public void setLar96(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar96</code>.
     */
    public Integer getLar96() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar98</code>.
     */
    public void setLar98(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar98</code>.
     */
    public Integer getLar98() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar100</code>.
     */
    public void setLar100(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar100</code>.
     */
    public Integer getLar100() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar102</code>.
     */
    public void setLar102(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar102</code>.
     */
    public Integer getLar102() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar104</code>.
     */
    public void setLar104(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar104</code>.
     */
    public Integer getLar104() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar106</code>.
     */
    public void setLar106(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar106</code>.
     */
    public Integer getLar106() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar108</code>.
     */
    public void setLar108(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar108</code>.
     */
    public Integer getLar108() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar110</code>.
     */
    public void setLar110(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar110</code>.
     */
    public Integer getLar110() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar112</code>.
     */
    public void setLar112(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar112</code>.
     */
    public Integer getLar112() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar114</code>.
     */
    public void setLar114(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar114</code>.
     */
    public Integer getLar114() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar116</code>.
     */
    public void setLar116(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar116</code>.
     */
    public Integer getLar116() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar118</code>.
     */
    public void setLar118(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar118</code>.
     */
    public Integer getLar118() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.estado</code>.
     */
    public void setEstado(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.estado</code>.
     */
    public String getEstado() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(22);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(25);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.id_sol_calidad</code>.
     */
    public void setIdSolCalidad(Long value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.id_sol_calidad</code>.
     */
    public Long getIdSolCalidad() {
        return (Long) get(26);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolCalLargoDedoRecord
     */
    public TabSolCalLargoDedoRecord() {
        super(TabSolCalLargoDedo.TAB_SOL_CAL_LARGO_DEDO);
    }

    /**
     * Create a detached, initialised TabSolCalLargoDedoRecord
     */
    public TabSolCalLargoDedoRecord(Long idSolCalLargoDedo, Integer lar80, Integer lar82, Integer lar84, Integer lar86, Integer lar88, Integer lar90, Integer lar92, Integer lar94, Integer lar96, Integer lar98, Integer lar100, Integer lar102, Integer lar104, Integer lar106, Integer lar108, Integer lar110, Integer lar112, Integer lar114, Integer lar116, Integer lar118, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, Long idSolCalidad) {
        super(TabSolCalLargoDedo.TAB_SOL_CAL_LARGO_DEDO);

        set(0, idSolCalLargoDedo);
        set(1, lar80);
        set(2, lar82);
        set(3, lar84);
        set(4, lar86);
        set(5, lar88);
        set(6, lar90);
        set(7, lar92);
        set(8, lar94);
        set(9, lar96);
        set(10, lar98);
        set(11, lar100);
        set(12, lar102);
        set(13, lar104);
        set(14, lar106);
        set(15, lar108);
        set(16, lar110);
        set(17, lar112);
        set(18, lar114);
        set(19, lar116);
        set(20, lar118);
        set(21, estado);
        set(22, fechaIngreso);
        set(23, fechaModifica);
        set(24, usuarioIngreso);
        set(25, usuarioModifica);
        set(26, idSolCalidad);
    }
}
