/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolicitud;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolicitudRecord extends UpdatableRecordImpl<TabSolicitudRecord> {

    private static final long serialVersionUID = -1676234955;

    /**
     * Setter for <code>public.tab_solicitud.id_solicitud</code>.
     */
    public void setIdSolicitud(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.id_solicitud</code>.
     */
    public Long getIdSolicitud() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_solicitud.nro_semana</code>.
     */
    public void setNroSemana(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.nro_semana</code>.
     */
    public Integer getNroSemana() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tab_solicitud.exportador</code>.
     */
    public void setExportador(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.exportador</code>.
     */
    public String getExportador() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tab_solicitud.cliente</code>.
     */
    public void setCliente(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.cliente</code>.
     */
    public String getCliente() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tab_solicitud.tipo_solicitud</code>.
     */
    public void setTipoSolicitud(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.tipo_solicitud</code>.
     */
    public String getTipoSolicitud() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tab_solicitud.productor</code>.
     */
    public void setProductor(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.productor</code>.
     */
    public String getProductor() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tab_solicitud.cod_productor</code>.
     */
    public void setCodProductor(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.cod_productor</code>.
     */
    public String getCodProductor() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tab_solicitud.cod_magap</code>.
     */
    public void setCodMagap(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.cod_magap</code>.
     */
    public String getCodMagap() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tab_solicitud.puerto_embarque</code>.
     */
    public void setPuertoEmbarque(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.puerto_embarque</code>.
     */
    public String getPuertoEmbarque() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.tab_solicitud.zona</code>.
     */
    public void setZona(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.zona</code>.
     */
    public String getZona() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.tab_solicitud.fecha_inicio</code>.
     */
    public void setFechaInicio(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.fecha_inicio</code>.
     */
    public LocalDateTime getFechaInicio() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.tab_solicitud.fecha_termino</code>.
     */
    public void setFechaTermino(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.fecha_termino</code>.
     */
    public LocalDateTime getFechaTermino() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.tab_solicitud.contenedor</code>.
     */
    public void setContenedor(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.contenedor</code>.
     */
    public String getContenedor() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.tab_solicitud.observacion</code>.
     */
    public void setObservacion(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.observacion</code>.
     */
    public String getObservacion() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.tab_solicitud.estado</code>.
     */
    public void setEstado(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.estado</code>.
     */
    public String getEstado() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.tab_solicitud.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>public.tab_solicitud.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>public.tab_solicitud.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.tab_solicitud.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>public.tab_solicitud.nom_evaluador_01</code>.
     */
    public void setNomEvaluador_01(String value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.nom_evaluador_01</code>.
     */
    public String getNomEvaluador_01() {
        return (String) get(19);
    }

    /**
     * Setter for <code>public.tab_solicitud.ci_evaluador_01</code>.
     */
    public void setCiEvaluador_01(String value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.ci_evaluador_01</code>.
     */
    public String getCiEvaluador_01() {
        return (String) get(20);
    }

    /**
     * Setter for <code>public.tab_solicitud.nom_evaluador_02</code>.
     */
    public void setNomEvaluador_02(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.nom_evaluador_02</code>.
     */
    public String getNomEvaluador_02() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.tab_solicitud.ci_evaluador_02</code>.
     */
    public void setCiEvaluador_02(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.tab_solicitud.ci_evaluador_02</code>.
     */
    public String getCiEvaluador_02() {
        return (String) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolicitudRecord
     */
    public TabSolicitudRecord() {
        super(TabSolicitud.TAB_SOLICITUD);
    }

    /**
     * Create a detached, initialised TabSolicitudRecord
     */
    public TabSolicitudRecord(Long idSolicitud, Integer nroSemana, String exportador, String cliente, String tipoSolicitud, String productor, String codProductor, String codMagap, String puertoEmbarque, String zona, LocalDateTime fechaInicio, LocalDateTime fechaTermino, String contenedor, String observacion, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, String nomEvaluador_01, String ciEvaluador_01, String nomEvaluador_02, String ciEvaluador_02) {
        super(TabSolicitud.TAB_SOLICITUD);

        set(0, idSolicitud);
        set(1, nroSemana);
        set(2, exportador);
        set(3, cliente);
        set(4, tipoSolicitud);
        set(5, productor);
        set(6, codProductor);
        set(7, codMagap);
        set(8, puertoEmbarque);
        set(9, zona);
        set(10, fechaInicio);
        set(11, fechaTermino);
        set(12, contenedor);
        set(13, observacion);
        set(14, estado);
        set(15, fechaIngreso);
        set(16, fechaModifica);
        set(17, usuarioIngreso);
        set(18, usuarioModifica);
        set(19, nomEvaluador_01);
        set(20, ciEvaluador_01);
        set(21, nomEvaluador_02);
        set(22, ciEvaluador_02);
    }
}
