/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolCalidad;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolCalidadRecord extends UpdatableRecordImpl<TabSolCalidadRecord> {

    private static final long serialVersionUID = 1859936205;

    /**
     * Setter for <code>public.tab_sol_calidad.id_sol_calidad</code>.
     */
    public void setIdSolCalidad(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.id_sol_calidad</code>.
     */
    public Long getIdSolCalidad() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.nom_marca</code>.
     */
    public void setNomMarca(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.nom_marca</code>.
     */
    public String getNomMarca() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.nro_qs</code>.
     */
    public void setNroQs(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.nro_qs</code>.
     */
    public String getNroQs() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.guia_transporte</code>.
     */
    public void setGuiaTransporte(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.guia_transporte</code>.
     */
    public String getGuiaTransporte() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.guia_remision</code>.
     */
    public void setGuiaRemision(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.guia_remision</code>.
     */
    public String getGuiaRemision() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.defectuoso</code>.
     */
    public void setDefectuoso(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.defectuoso</code>.
     */
    public Integer getDefectuoso() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.tarjeta_embarque</code>.
     */
    public void setTarjetaEmbarque(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.tarjeta_embarque</code>.
     */
    public String getTarjetaEmbarque() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.total_cluster</code>.
     */
    public void setTotalCluster(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.total_cluster</code>.
     */
    public Integer getTotalCluster() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.total_defecto</code>.
     */
    public void setTotalDefecto(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.total_defecto</code>.
     */
    public Integer getTotalDefecto() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.calidad</code>.
     */
    public void setCalidad(Float value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.calidad</code>.
     */
    public Float getCalidad() {
        return (Float) get(9);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.calibracion</code>.
     */
    public void setCalibracion(Float value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.calibracion</code>.
     */
    public Float getCalibracion() {
        return (Float) get(10);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.largo_dedo</code>.
     */
    public void setLargoDedo(Float value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.largo_dedo</code>.
     */
    public Float getLargoDedo() {
        return (Float) get(11);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.total_peso</code>.
     */
    public void setTotalPeso(Float value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.total_peso</code>.
     */
    public Float getTotalPeso() {
        return (Float) get(12);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.peso_promedio</code>.
     */
    public void setPesoPromedio(Float value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.peso_promedio</code>.
     */
    public Float getPesoPromedio() {
        return (Float) get(13);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.mayor_defecto_seleccion</code>.
     */
    public void setMayorDefectoSeleccion(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.mayor_defecto_seleccion</code>.
     */
    public String getMayorDefectoSeleccion() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.mayor_defecto_empaque</code>.
     */
    public void setMayorDefectoEmpaque(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.mayor_defecto_empaque</code>.
     */
    public String getMayorDefectoEmpaque() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.estado</code>.
     */
    public void setEstado(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.estado</code>.
     */
    public String getEstado() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.id_solicitud</code>.
     */
    public void setIdSolicitud(Long value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.id_solicitud</code>.
     */
    public Long getIdSolicitud() {
        return (Long) get(21);
    }

    /**
     * Setter for <code>public.tab_sol_calidad.id_sol_productor</code>.
     */
    public void setIdSolProductor(Long value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.tab_sol_calidad.id_sol_productor</code>.
     */
    public Long getIdSolProductor() {
        return (Long) get(22);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolCalidadRecord
     */
    public TabSolCalidadRecord() {
        super(TabSolCalidad.TAB_SOL_CALIDAD);
    }

    /**
     * Create a detached, initialised TabSolCalidadRecord
     */
    public TabSolCalidadRecord(Long idSolCalidad, String nomMarca, String nroQs, String guiaTransporte, String guiaRemision, Integer defectuoso, String tarjetaEmbarque, Integer totalCluster, Integer totalDefecto, Float calidad, Float calibracion, Float largoDedo, Float totalPeso, Float pesoPromedio, String mayorDefectoSeleccion, String mayorDefectoEmpaque, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, Long idSolicitud, Long idSolProductor) {
        super(TabSolCalidad.TAB_SOL_CALIDAD);

        set(0, idSolCalidad);
        set(1, nomMarca);
        set(2, nroQs);
        set(3, guiaTransporte);
        set(4, guiaRemision);
        set(5, defectuoso);
        set(6, tarjetaEmbarque);
        set(7, totalCluster);
        set(8, totalDefecto);
        set(9, calidad);
        set(10, calibracion);
        set(11, largoDedo);
        set(12, totalPeso);
        set(13, pesoPromedio);
        set(14, mayorDefectoSeleccion);
        set(15, mayorDefectoEmpaque);
        set(16, estado);
        set(17, fechaIngreso);
        set(18, fechaModifica);
        set(19, usuarioIngreso);
        set(20, usuarioModifica);
        set(21, idSolicitud);
        set(22, idSolProductor);
    }
}
