/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolProceso;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record17;
import org.jooq.Row17;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolProcesoRecord extends UpdatableRecordImpl<TabSolProcesoRecord> implements Record17<Long, Integer, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long, Long> {

    private static final long serialVersionUID = 1912941756;

    /**
     * Setter for <code>public.tab_sol_proceso.id_sol_proceso</code>.
     */
    public void setIdSolProceso(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.id_sol_proceso</code>.
     */
    public Long getIdSolProceso() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.caja_procesada</code>.
     */
    public void setCajaProcesada(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.caja_procesada</code>.
     */
    public Integer getCajaProcesada() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.tipo_fruta</code>.
     */
    public void setTipoFruta(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.tipo_fruta</code>.
     */
    public String getTipoFruta() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.tipo_funda</code>.
     */
    public void setTipoFunda(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.tipo_funda</code>.
     */
    public String getTipoFunda() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.densidad_funda</code>.
     */
    public void setDensidadFunda(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.densidad_funda</code>.
     */
    public String getDensidadFunda() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.tipo_caja</code>.
     */
    public void setTipoCaja(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.tipo_caja</code>.
     */
    public String getTipoCaja() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.tipo_presentacion</code>.
     */
    public void setTipoPresentacion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.tipo_presentacion</code>.
     */
    public String getTipoPresentacion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.tipo_estiba</code>.
     */
    public void setTipoEstiba(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.tipo_estiba</code>.
     */
    public String getTipoEstiba() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.tiempo_descarga</code>.
     */
    public void setTiempoDescarga(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.tiempo_descarga</code>.
     */
    public String getTiempoDescarga() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.tipo_cantulina</code>.
     */
    public void setTipoCantulina(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.tipo_cantulina</code>.
     */
    public String getTipoCantulina() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.estado</code>.
     */
    public void setEstado(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.estado</code>.
     */
    public String getEstado() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.id_solicitud</code>.
     */
    public void setIdSolicitud(Long value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.id_solicitud</code>.
     */
    public Long getIdSolicitud() {
        return (Long) get(15);
    }

    /**
     * Setter for <code>public.tab_sol_proceso.id_sol_productor</code>.
     */
    public void setIdSolProductor(Long value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.tab_sol_proceso.id_sol_productor</code>.
     */
    public Long getIdSolProductor() {
        return (Long) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record17 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row17<Long, Integer, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long, Long> fieldsRow() {
        return (Row17) super.fieldsRow();
    }

    @Override
    public Row17<Long, Integer, String, String, String, String, String, String, String, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long, Long> valuesRow() {
        return (Row17) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TabSolProceso.TAB_SOL_PROCESO.ID_SOL_PROCESO;
    }

    @Override
    public Field<Integer> field2() {
        return TabSolProceso.TAB_SOL_PROCESO.CAJA_PROCESADA;
    }

    @Override
    public Field<String> field3() {
        return TabSolProceso.TAB_SOL_PROCESO.TIPO_FRUTA;
    }

    @Override
    public Field<String> field4() {
        return TabSolProceso.TAB_SOL_PROCESO.TIPO_FUNDA;
    }

    @Override
    public Field<String> field5() {
        return TabSolProceso.TAB_SOL_PROCESO.DENSIDAD_FUNDA;
    }

    @Override
    public Field<String> field6() {
        return TabSolProceso.TAB_SOL_PROCESO.TIPO_CAJA;
    }

    @Override
    public Field<String> field7() {
        return TabSolProceso.TAB_SOL_PROCESO.TIPO_PRESENTACION;
    }

    @Override
    public Field<String> field8() {
        return TabSolProceso.TAB_SOL_PROCESO.TIPO_ESTIBA;
    }

    @Override
    public Field<String> field9() {
        return TabSolProceso.TAB_SOL_PROCESO.TIEMPO_DESCARGA;
    }

    @Override
    public Field<String> field10() {
        return TabSolProceso.TAB_SOL_PROCESO.TIPO_CANTULINA;
    }

    @Override
    public Field<String> field11() {
        return TabSolProceso.TAB_SOL_PROCESO.ESTADO;
    }

    @Override
    public Field<LocalDateTime> field12() {
        return TabSolProceso.TAB_SOL_PROCESO.FECHA_INGRESO;
    }

    @Override
    public Field<LocalDateTime> field13() {
        return TabSolProceso.TAB_SOL_PROCESO.FECHA_MODIFICA;
    }

    @Override
    public Field<Integer> field14() {
        return TabSolProceso.TAB_SOL_PROCESO.USUARIO_INGRESO;
    }

    @Override
    public Field<Integer> field15() {
        return TabSolProceso.TAB_SOL_PROCESO.USUARIO_MODIFICA;
    }

    @Override
    public Field<Long> field16() {
        return TabSolProceso.TAB_SOL_PROCESO.ID_SOLICITUD;
    }

    @Override
    public Field<Long> field17() {
        return TabSolProceso.TAB_SOL_PROCESO.ID_SOL_PRODUCTOR;
    }

    @Override
    public Long component1() {
        return getIdSolProceso();
    }

    @Override
    public Integer component2() {
        return getCajaProcesada();
    }

    @Override
    public String component3() {
        return getTipoFruta();
    }

    @Override
    public String component4() {
        return getTipoFunda();
    }

    @Override
    public String component5() {
        return getDensidadFunda();
    }

    @Override
    public String component6() {
        return getTipoCaja();
    }

    @Override
    public String component7() {
        return getTipoPresentacion();
    }

    @Override
    public String component8() {
        return getTipoEstiba();
    }

    @Override
    public String component9() {
        return getTiempoDescarga();
    }

    @Override
    public String component10() {
        return getTipoCantulina();
    }

    @Override
    public String component11() {
        return getEstado();
    }

    @Override
    public LocalDateTime component12() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime component13() {
        return getFechaModifica();
    }

    @Override
    public Integer component14() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer component15() {
        return getUsuarioModifica();
    }

    @Override
    public Long component16() {
        return getIdSolicitud();
    }

    @Override
    public Long component17() {
        return getIdSolProductor();
    }

    @Override
    public Long value1() {
        return getIdSolProceso();
    }

    @Override
    public Integer value2() {
        return getCajaProcesada();
    }

    @Override
    public String value3() {
        return getTipoFruta();
    }

    @Override
    public String value4() {
        return getTipoFunda();
    }

    @Override
    public String value5() {
        return getDensidadFunda();
    }

    @Override
    public String value6() {
        return getTipoCaja();
    }

    @Override
    public String value7() {
        return getTipoPresentacion();
    }

    @Override
    public String value8() {
        return getTipoEstiba();
    }

    @Override
    public String value9() {
        return getTiempoDescarga();
    }

    @Override
    public String value10() {
        return getTipoCantulina();
    }

    @Override
    public String value11() {
        return getEstado();
    }

    @Override
    public LocalDateTime value12() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime value13() {
        return getFechaModifica();
    }

    @Override
    public Integer value14() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer value15() {
        return getUsuarioModifica();
    }

    @Override
    public Long value16() {
        return getIdSolicitud();
    }

    @Override
    public Long value17() {
        return getIdSolProductor();
    }

    @Override
    public TabSolProcesoRecord value1(Long value) {
        setIdSolProceso(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value2(Integer value) {
        setCajaProcesada(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value3(String value) {
        setTipoFruta(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value4(String value) {
        setTipoFunda(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value5(String value) {
        setDensidadFunda(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value6(String value) {
        setTipoCaja(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value7(String value) {
        setTipoPresentacion(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value8(String value) {
        setTipoEstiba(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value9(String value) {
        setTiempoDescarga(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value10(String value) {
        setTipoCantulina(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value11(String value) {
        setEstado(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value12(LocalDateTime value) {
        setFechaIngreso(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value13(LocalDateTime value) {
        setFechaModifica(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value14(Integer value) {
        setUsuarioIngreso(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value15(Integer value) {
        setUsuarioModifica(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value16(Long value) {
        setIdSolicitud(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord value17(Long value) {
        setIdSolProductor(value);
        return this;
    }

    @Override
    public TabSolProcesoRecord values(Long value1, Integer value2, String value3, String value4, String value5, String value6, String value7, String value8, String value9, String value10, String value11, LocalDateTime value12, LocalDateTime value13, Integer value14, Integer value15, Long value16, Long value17) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolProcesoRecord
     */
    public TabSolProcesoRecord() {
        super(TabSolProceso.TAB_SOL_PROCESO);
    }

    /**
     * Create a detached, initialised TabSolProcesoRecord
     */
    public TabSolProcesoRecord(Long idSolProceso, Integer cajaProcesada, String tipoFruta, String tipoFunda, String densidadFunda, String tipoCaja, String tipoPresentacion, String tipoEstiba, String tiempoDescarga, String tipoCantulina, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, Long idSolicitud, Long idSolProductor) {
        super(TabSolProceso.TAB_SOL_PROCESO);

        set(0, idSolProceso);
        set(1, cajaProcesada);
        set(2, tipoFruta);
        set(3, tipoFunda);
        set(4, densidadFunda);
        set(5, tipoCaja);
        set(6, tipoPresentacion);
        set(7, tipoEstiba);
        set(8, tiempoDescarga);
        set(9, tipoCantulina);
        set(10, estado);
        set(11, fechaIngreso);
        set(12, fechaModifica);
        set(13, usuarioIngreso);
        set(14, usuarioModifica);
        set(15, idSolicitud);
        set(16, idSolProductor);
    }
}
