/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolProductor;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolProductorRecord extends UpdatableRecordImpl<TabSolProductorRecord> implements Record8<Long, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long> {

    private static final long serialVersionUID = 1385734299;

    /**
     * Setter for <code>public.tab_sol_productor.id_sol_productor</code>.
     */
    public void setIdSolProductor(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_sol_productor.id_sol_productor</code>.
     */
    public Long getIdSolProductor() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_sol_productor.nombre</code>.
     */
    public void setNombre(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_sol_productor.nombre</code>.
     */
    public String getNombre() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.tab_sol_productor.estado</code>.
     */
    public void setEstado(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_sol_productor.estado</code>.
     */
    public String getEstado() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.tab_sol_productor.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_sol_productor.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.tab_sol_productor.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_sol_productor.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.tab_sol_productor.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_sol_productor.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tab_sol_productor.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_sol_productor.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.tab_sol_productor.id_solicitud</code>.
     */
    public void setIdSolicitud(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_sol_productor.id_solicitud</code>.
     */
    public Long getIdSolicitud() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, String, String, LocalDateTime, LocalDateTime, Integer, Integer, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return TabSolProductor.TAB_SOL_PRODUCTOR.ID_SOL_PRODUCTOR;
    }

    @Override
    public Field<String> field2() {
        return TabSolProductor.TAB_SOL_PRODUCTOR.NOMBRE;
    }

    @Override
    public Field<String> field3() {
        return TabSolProductor.TAB_SOL_PRODUCTOR.ESTADO;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return TabSolProductor.TAB_SOL_PRODUCTOR.FECHA_INGRESO;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return TabSolProductor.TAB_SOL_PRODUCTOR.FECHA_MODIFICA;
    }

    @Override
    public Field<Integer> field6() {
        return TabSolProductor.TAB_SOL_PRODUCTOR.USUARIO_INGRESO;
    }

    @Override
    public Field<Integer> field7() {
        return TabSolProductor.TAB_SOL_PRODUCTOR.USUARIO_MODIFICA;
    }

    @Override
    public Field<Long> field8() {
        return TabSolProductor.TAB_SOL_PRODUCTOR.ID_SOLICITUD;
    }

    @Override
    public Long component1() {
        return getIdSolProductor();
    }

    @Override
    public String component2() {
        return getNombre();
    }

    @Override
    public String component3() {
        return getEstado();
    }

    @Override
    public LocalDateTime component4() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime component5() {
        return getFechaModifica();
    }

    @Override
    public Integer component6() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer component7() {
        return getUsuarioModifica();
    }

    @Override
    public Long component8() {
        return getIdSolicitud();
    }

    @Override
    public Long value1() {
        return getIdSolProductor();
    }

    @Override
    public String value2() {
        return getNombre();
    }

    @Override
    public String value3() {
        return getEstado();
    }

    @Override
    public LocalDateTime value4() {
        return getFechaIngreso();
    }

    @Override
    public LocalDateTime value5() {
        return getFechaModifica();
    }

    @Override
    public Integer value6() {
        return getUsuarioIngreso();
    }

    @Override
    public Integer value7() {
        return getUsuarioModifica();
    }

    @Override
    public Long value8() {
        return getIdSolicitud();
    }

    @Override
    public TabSolProductorRecord value1(Long value) {
        setIdSolProductor(value);
        return this;
    }

    @Override
    public TabSolProductorRecord value2(String value) {
        setNombre(value);
        return this;
    }

    @Override
    public TabSolProductorRecord value3(String value) {
        setEstado(value);
        return this;
    }

    @Override
    public TabSolProductorRecord value4(LocalDateTime value) {
        setFechaIngreso(value);
        return this;
    }

    @Override
    public TabSolProductorRecord value5(LocalDateTime value) {
        setFechaModifica(value);
        return this;
    }

    @Override
    public TabSolProductorRecord value6(Integer value) {
        setUsuarioIngreso(value);
        return this;
    }

    @Override
    public TabSolProductorRecord value7(Integer value) {
        setUsuarioModifica(value);
        return this;
    }

    @Override
    public TabSolProductorRecord value8(Long value) {
        setIdSolicitud(value);
        return this;
    }

    @Override
    public TabSolProductorRecord values(Long value1, String value2, String value3, LocalDateTime value4, LocalDateTime value5, Integer value6, Integer value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolProductorRecord
     */
    public TabSolProductorRecord() {
        super(TabSolProductor.TAB_SOL_PRODUCTOR);
    }

    /**
     * Create a detached, initialised TabSolProductorRecord
     */
    public TabSolProductorRecord(Long idSolProductor, String nombre, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, Long idSolicitud) {
        super(TabSolProductor.TAB_SOL_PRODUCTOR);

        set(0, idSolProductor);
        set(1, nombre);
        set(2, estado);
        set(3, fechaIngreso);
        set(4, fechaModifica);
        set(5, usuarioIngreso);
        set(6, usuarioModifica);
        set(7, idSolicitud);
    }
}
