/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolCalLargoDedo;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolCalLargoDedoRecord extends UpdatableRecordImpl<TabSolCalLargoDedoRecord> {

    private static final long serialVersionUID = -2128684910;

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.id_sol_cal_largo_dedo</code>.
     */
    public void setIdSolCalLargoDedo(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.id_sol_cal_largo_dedo</code>.
     */
    public Long getIdSolCalLargoDedo() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_80</code>.
     */
    public void setLar_80(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_80</code>.
     */
    public Integer getLar_80() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_82</code>.
     */
    public void setLar_82(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_82</code>.
     */
    public Integer getLar_82() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_84</code>.
     */
    public void setLar_84(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_84</code>.
     */
    public Integer getLar_84() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_86</code>.
     */
    public void setLar_86(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_86</code>.
     */
    public Integer getLar_86() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_88</code>.
     */
    public void setLar_88(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_88</code>.
     */
    public Integer getLar_88() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_90</code>.
     */
    public void setLar_90(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_90</code>.
     */
    public Integer getLar_90() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_92</code>.
     */
    public void setLar_92(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_92</code>.
     */
    public Integer getLar_92() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_94</code>.
     */
    public void setLar_94(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_94</code>.
     */
    public Integer getLar_94() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_96</code>.
     */
    public void setLar_96(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_96</code>.
     */
    public Integer getLar_96() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_98</code>.
     */
    public void setLar_98(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_98</code>.
     */
    public Integer getLar_98() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_100</code>.
     */
    public void setLar_100(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_100</code>.
     */
    public Integer getLar_100() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_102</code>.
     */
    public void setLar_102(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_102</code>.
     */
    public Integer getLar_102() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_104</code>.
     */
    public void setLar_104(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_104</code>.
     */
    public Integer getLar_104() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_106</code>.
     */
    public void setLar_106(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_106</code>.
     */
    public Integer getLar_106() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_108</code>.
     */
    public void setLar_108(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_108</code>.
     */
    public Integer getLar_108() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_110</code>.
     */
    public void setLar_110(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_110</code>.
     */
    public Integer getLar_110() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_112</code>.
     */
    public void setLar_112(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_112</code>.
     */
    public Integer getLar_112() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_114</code>.
     */
    public void setLar_114(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_114</code>.
     */
    public Integer getLar_114() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_116</code>.
     */
    public void setLar_116(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_116</code>.
     */
    public Integer getLar_116() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.lar_118</code>.
     */
    public void setLar_118(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.lar_118</code>.
     */
    public Integer getLar_118() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.estado</code>.
     */
    public void setEstado(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.estado</code>.
     */
    public String getEstado() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(22);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(25);
    }

    /**
     * Setter for <code>public.tab_sol_cal_largo_dedo.id_sol_calidad</code>.
     */
    public void setIdSolCalidad(Long value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_largo_dedo.id_sol_calidad</code>.
     */
    public Long getIdSolCalidad() {
        return (Long) get(26);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolCalLargoDedoRecord
     */
    public TabSolCalLargoDedoRecord() {
        super(TabSolCalLargoDedo.TAB_SOL_CAL_LARGO_DEDO);
    }

    /**
     * Create a detached, initialised TabSolCalLargoDedoRecord
     */
    public TabSolCalLargoDedoRecord(Long idSolCalLargoDedo, Integer lar_80, Integer lar_82, Integer lar_84, Integer lar_86, Integer lar_88, Integer lar_90, Integer lar_92, Integer lar_94, Integer lar_96, Integer lar_98, Integer lar_100, Integer lar_102, Integer lar_104, Integer lar_106, Integer lar_108, Integer lar_110, Integer lar_112, Integer lar_114, Integer lar_116, Integer lar_118, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, Long idSolCalidad) {
        super(TabSolCalLargoDedo.TAB_SOL_CAL_LARGO_DEDO);

        set(0, idSolCalLargoDedo);
        set(1, lar_80);
        set(2, lar_82);
        set(3, lar_84);
        set(4, lar_86);
        set(5, lar_88);
        set(6, lar_90);
        set(7, lar_92);
        set(8, lar_94);
        set(9, lar_96);
        set(10, lar_98);
        set(11, lar_100);
        set(12, lar_102);
        set(13, lar_104);
        set(14, lar_106);
        set(15, lar_108);
        set(16, lar_110);
        set(17, lar_112);
        set(18, lar_114);
        set(19, lar_116);
        set(20, lar_118);
        set(21, estado);
        set(22, fechaIngreso);
        set(23, fechaModifica);
        set(24, usuarioIngreso);
        set(25, usuarioModifica);
        set(26, idSolCalidad);
    }
}
