/*
 * This file is generated by jOOQ.
 */
package com.inspector.ws.db.schema.tables.records;


import com.inspector.ws.db.schema.tables.TabSolCalCalibre;

import java.time.LocalDateTime;

import javax.annotation.processing.Generated;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TabSolCalCalibreRecord extends UpdatableRecordImpl<TabSolCalCalibreRecord> {

    private static final long serialVersionUID = -232392473;

    /**
     * Setter for <code>public.tab_sol_cal_calibre.id_sol_cal_calibre</code>.
     */
    public void setIdSolCalCalibre(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.id_sol_cal_calibre</code>.
     */
    public Long getIdSolCalCalibre() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_ug</code>.
     */
    public void setCalUg(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_ug</code>.
     */
    public Integer getCalUg() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_og</code>.
     */
    public void setCalOg(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_og</code>.
     */
    public Integer getCalOg() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_37</code>.
     */
    public void setCal_37(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_37</code>.
     */
    public Integer getCal_37() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_38</code>.
     */
    public void setCal_38(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_38</code>.
     */
    public Integer getCal_38() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_39</code>.
     */
    public void setCal_39(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_39</code>.
     */
    public Integer getCal_39() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_40</code>.
     */
    public void setCal_40(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_40</code>.
     */
    public Integer getCal_40() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_41</code>.
     */
    public void setCal_41(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_41</code>.
     */
    public Integer getCal_41() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_42</code>.
     */
    public void setCal_42(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_42</code>.
     */
    public Integer getCal_42() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_43</code>.
     */
    public void setCal_43(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_43</code>.
     */
    public Integer getCal_43() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_44</code>.
     */
    public void setCal_44(Integer value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_44</code>.
     */
    public Integer getCal_44() {
        return (Integer) get(10);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_45</code>.
     */
    public void setCal_45(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_45</code>.
     */
    public Integer getCal_45() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_46</code>.
     */
    public void setCal_46(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_46</code>.
     */
    public Integer getCal_46() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_47</code>.
     */
    public void setCal_47(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_47</code>.
     */
    public Integer getCal_47() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_48</code>.
     */
    public void setCal_48(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_48</code>.
     */
    public Integer getCal_48() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_49</code>.
     */
    public void setCal_49(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_49</code>.
     */
    public Integer getCal_49() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_50</code>.
     */
    public void setCal_50(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_50</code>.
     */
    public Integer getCal_50() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_51</code>.
     */
    public void setCal_51(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_51</code>.
     */
    public Integer getCal_51() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_52</code>.
     */
    public void setCal_52(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_52</code>.
     */
    public Integer getCal_52() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_53</code>.
     */
    public void setCal_53(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_53</code>.
     */
    public Integer getCal_53() {
        return (Integer) get(19);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.cal_54</code>.
     */
    public void setCal_54(Integer value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.cal_54</code>.
     */
    public Integer getCal_54() {
        return (Integer) get(20);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.estado</code>.
     */
    public void setEstado(String value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.estado</code>.
     */
    public String getEstado() {
        return (String) get(21);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.fecha_ingreso</code>.
     */
    public void setFechaIngreso(LocalDateTime value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.fecha_ingreso</code>.
     */
    public LocalDateTime getFechaIngreso() {
        return (LocalDateTime) get(22);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.fecha_modifica</code>.
     */
    public void setFechaModifica(LocalDateTime value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.fecha_modifica</code>.
     */
    public LocalDateTime getFechaModifica() {
        return (LocalDateTime) get(23);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.usuario_ingreso</code>.
     */
    public void setUsuarioIngreso(Integer value) {
        set(24, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.usuario_ingreso</code>.
     */
    public Integer getUsuarioIngreso() {
        return (Integer) get(24);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.usuario_modifica</code>.
     */
    public void setUsuarioModifica(Integer value) {
        set(25, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.usuario_modifica</code>.
     */
    public Integer getUsuarioModifica() {
        return (Integer) get(25);
    }

    /**
     * Setter for <code>public.tab_sol_cal_calibre.id_sol_calidad</code>.
     */
    public void setIdSolCalidad(Long value) {
        set(26, value);
    }

    /**
     * Getter for <code>public.tab_sol_cal_calibre.id_sol_calidad</code>.
     */
    public Long getIdSolCalidad() {
        return (Long) get(26);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TabSolCalCalibreRecord
     */
    public TabSolCalCalibreRecord() {
        super(TabSolCalCalibre.TAB_SOL_CAL_CALIBRE);
    }

    /**
     * Create a detached, initialised TabSolCalCalibreRecord
     */
    public TabSolCalCalibreRecord(Long idSolCalCalibre, Integer calUg, Integer calOg, Integer cal_37, Integer cal_38, Integer cal_39, Integer cal_40, Integer cal_41, Integer cal_42, Integer cal_43, Integer cal_44, Integer cal_45, Integer cal_46, Integer cal_47, Integer cal_48, Integer cal_49, Integer cal_50, Integer cal_51, Integer cal_52, Integer cal_53, Integer cal_54, String estado, LocalDateTime fechaIngreso, LocalDateTime fechaModifica, Integer usuarioIngreso, Integer usuarioModifica, Long idSolCalidad) {
        super(TabSolCalCalibre.TAB_SOL_CAL_CALIBRE);

        set(0, idSolCalCalibre);
        set(1, calUg);
        set(2, calOg);
        set(3, cal_37);
        set(4, cal_38);
        set(5, cal_39);
        set(6, cal_40);
        set(7, cal_41);
        set(8, cal_42);
        set(9, cal_43);
        set(10, cal_44);
        set(11, cal_45);
        set(12, cal_46);
        set(13, cal_47);
        set(14, cal_48);
        set(15, cal_49);
        set(16, cal_50);
        set(17, cal_51);
        set(18, cal_52);
        set(19, cal_53);
        set(20, cal_54);
        set(21, estado);
        set(22, fechaIngreso);
        set(23, fechaModifica);
        set(24, usuarioIngreso);
        set(25, usuarioModifica);
        set(26, idSolCalidad);
    }
}
